### ISSUE TITLE
ListView::getItemRow/1 return non-empty vector when there isn't columns. 

### ISSUE THREAD

**Issue by Kvaz1r** [texus/TGUI#109]
ListView::getItemRow/1 return non-empty vector when there isn't columns. But according to [the documentation](https://github.com/texus/TGUI/blob/f9677bebe64953fff38ba1d10ba48b2da249c126/include/TGUI/Widgets/ListView.hpp#L378) 

> The returned list has the same length as the amount of columns.

I don't know why it possible display items without columns and why it possible only for zero column but it should be documented or fixed for consistency.  

MCVE:
```
#include <TGUI/TGUI.hpp>
#include <iostream>

int main()
{
    sf::RenderWindow window(sf::VideoMode(400, 300), "TGUI window");
    tgui::Gui gui(window);

    auto panel = tgui::ScrollablePanel::create();
    auto listView = tgui::ListView::create();
    listView->addItem({ "1","2" });
    std::cout << "Column count = "<<listView->getColumnCount() << '\n';
    std::cout << "getItemRow(0).size = " << listView->getItemRow(0).size() << '\n';

    panel->add(listView);
    gui.add(panel);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
            gui.handleEvent(event);
        }

        window.clear();
        gui.draw();
        window.display();
    }
}
```

Output:

> Column count = 0
> getItemRow(0).size = 1

**Comment by texus** [comment]
I agree that this could be better documented.

The ListView can basically be used in 2 different ways, and you are combining both of them.
It can works as a column-based ListView widget where you have to add columns to it and where each item consists of a row of strings. If you however don't set any columns at all, it works similarly to a ListBox, but with the additional ability to add icons next to your items and separator lines between items.

The getItemRow function doesn't really make sense when you aren't using columns. In this mode you would just use getItem instead. Technically there is one column, so getItemRow is still doing what is documented.
I can't really change getColumnCount to return 1 because that would give unexpected results when using removeAllColumns and addColumn.

**Comment by Kvaz1r** [comment]
Right, it make sense now.
