### ISSUE TITLE
Multiline item is corrupting ListView.  

### ISSUE THREAD

**Issue by Kvaz1r** [texus/TGUI#118]
It's totally understandable that single item from ListView shouldn't contain really many lines (maybe only one) but if it is contain several lines all other should be displayed correctly. 
Maybe solution is to add ellipsis for such case and for cases with long lines. 

MCVE:

```
#include <TGUI/TGUI.hpp>
#include <iostream>

class MyFrame
{
public:
    MyFrame()
    {
        window.create(sf::VideoMode(800, 600), "TGUI window");
        gui.setTarget(window);
        auto list = tgui::ListView::create();
        list->setSize(window.getSize().x, window.getSize().y);
        list->addColumn(L"   ID   ");
        list->addColumn(L"   Data   ");
        list->setExpandLastColumn(true);
        list->addItem({ "1","One line"});
        list->addItem({ "2","Multiline\nMultiline" });
        list->addItem({ "3","Again one line" });
        gui.add(list);
       
    }
    void main()
    {
        while (window.isOpen())
        {
            sf::Event event;
            while (window.pollEvent(event))
            {
                if (event.type == sf::Event::Closed)
                    window.close();
                gui.handleEvent(event);
            }
            window.clear();
            gui.draw();
            window.display();
        }
    }

private:
    sf::RenderWindow window;
    tgui::Gui gui;
};

int main()
{
    MyFrame().main();
}
```

**Comment by texus** [comment]
Most widgets don't support text with a newline in them and will produce undefined behavior (e.g. edit box will show the text outside the box). I don't really consider this a bug, these widgets simply don't support multiline text. In the future TGUI might silently drop the second line and only display the first one in all those widgets, but for the moment the behavior depends on the widget.

Just because it currently only supports single lines doesn't mean it has to remain like that though. If you were to send a PR where the height of the item becomes larger when some text contains a newline then I would definitely merge it.

I don't feel like displaying an ellipsis is the right behavior if there is no way to actually see the remaining text, it makes more sense in cases where the text just doesn't fit and it would be displayed if the box is resized.
Support for displaying an ellipsis should ideally also be implemented on a different level (in some Text class so that any widget would be able to set some flag to indicate whether text should be cut-off, word-wrapped or replaced by an ellipsis), but this part of the code shouldn't be touched before the 0.9 rewrites are finished.

**Comment by Kvaz1r** [comment]
> Just because it currently only supports single lines doesn't mean it has to remain like that though. If you were to send a PR where the height of the item becomes larger when some text contains a newline then I would definitely merge it.

In such case I definitely will try to implement it somewhen(it's hard because need to keep value of all items height to scroll correctly).

**Comment by Kvaz1r** [comment]
It seems that the game is not worth the candle and issue just not very fits to ListView. I will prevent such cases outside before set value to Item.
