### ISSUE TITLE
Newly added MenuBar item is already connected to signals when created with a hierarchy of a previously existing item

### ISSUE THREAD

**Issue by x-qq** [texus/TGUI#121]
Is it intended that signal connections are not removed when MenuBar items are removed with removeMenuItems ? When I add a menubar item with previously existed hierarchy it has signal connections of a removed item.

Example:
```
#include <TGUI/TGUI.hpp>
#include <iostream>

void hello () {
    std::cout << "hello" << std::endl;
}

int main() {
    sf::RenderWindow window(sf::VideoMode(800, 600), "TGUI window");
    window.setFramerateLimit(60);

    tgui::Gui gui(window);

    auto menu = tgui::MenuBar::create();

    menu->addMenuItem({"File", "Recent", "foo.pdf"});
    menu->connectMenuItem({"File", "Recent", "foo.pdf"}, hello);
    menu->removeMenuItems("File");
    menu->addMenuItem({"File", "Recent", "foo.pdf"});

    gui.add(menu);

    while (window.isOpen()){
        sf::Event event;
        while (window.pollEvent(event)) {
            if (event.type == sf::Event::Closed) window.close();

            gui.handleEvent(event);
        }

        window.clear();
        gui.draw();
        window.display();
    }

    return EXIT_SUCCESS;
}
```

I was not expecting that the callback would be called with the new menu item.

**Comment by texus** [comment]
I never thought about this case so it wasn't really intentional, but I think it is the correct behavior given how connectMenuItem works.

Before the connectMenuItem function was added, you had to use the MenuItemClicked signal which just gives a callback when ANY menu item has been clicked. The ability to connect to a single menu item was requested several times so I ended up adding the connectMenuItem function that allows you to do this.

The connectMenuItem function works by doing what you would normally do in your own code if it didn't exist: connect to the MenuItemClicked signal and if the hierarchy matches your item then execute your code. The function stores no state of the menu bar, it has no idea whether menus exist or not, it is just provided for convenience to only call your callback function when the clicked item matched a certain hierarchy.

**Comment by texus** [comment]
I consider the behavior to be a feature, since it allows setting the signals for all possible menu items and afterwards freely remove and add items without having to reconnect the callbacks. But since it could be unexpected behavior I have now added a remark in the documentation of the connectMenuItem function.
