### ISSUE TITLE
gui builder, How to set up a working directory?

### ISSUE THREAD

**Issue by colesnicov** [texus/TGUI#156]
Hi. I work with **Ubuntu**. Problem with **GUI_BUILDER**, Does not respect the path in which it was run.

For example:
I have GUI_BUILDER in the folder `~/opt/gui_builder`

I am in the directory `~/project/res` in which I would like to have Forms created. I **also have pictures in this directory** that I want to use in Forms.

Run the command:

`~/opt/gui_builder/gui_builder`

I will create a Form and have it saved (just click save) and the Form will be saved in the `~/opt/gui_builder/form.txt` directory. Why not to `~/project/res/form.txt`? How to achieve this?

**Comment by texus** [comment]
It sets the working directory to `~/opt/gui_builder` because that is where its resources are.
The filename can be an absolute path. Instead of creating a file called "form.txt", just name it "/home/USER/project/res/form.txt". You can change the name of an existing form in the properties on the right side when you click on the form instead of a widget inside it. If you save it afterwards then it will be saved to the new location.

With a recent 0.9-dev version you will get a file dialog when creating or loading a form, that way it is easier to understand where the file goes exactly. I just realized that the "default path" might be broken in that version, but I'll look into that later so that hopefully it will also remember the last location where you loaded a form so that you don't have to browse to it each time you create a new form.

**Comment by colesnicov** [comment]
I do not want to use absolute paths, in the program I have AssetManager which accepts relative path names, then I have to edit those forms manually.

0.9, that sounds good. I'm waiting for the release to come out. And even such a smaller idea, will it be possible in version 0.9 to enter the path to the directory where I have resources? Then it would be possible to use relative paths for resources. Now I have to copy the folder with my resources to the Gui_builder directory for each Form.

**Comment by texus** [comment]
The form path isn't saved anywhere, it is only part of the gui builder. There is no problem in using an absolute path for the form file.

The pictures is a bigger problem, because there I think it will indeed keep loading relative to "~/opt/gui_builder" and you would have to use an absolute path which is understandably undesirable. Unfortunately there is no solution for this yet. Form files still have to be manually edited to correct the resource directory. I still have to look for a solution for this, mostly the way themes need to be loaded is problematic (because they are part of the gui builder directory but when loading the form from your program they might suddenly have a different relative path).

TGUI 0.9 should be ready within the next two months.
