### ISSUE TITLE
Building static TGUI with mingw is not static - Backend GLFW_OPENGL3 

### ISSUE THREAD

**Issue by dmg103** [texus/TGUI#166]
I've been trying to compile TGUI **statically** using **mingw** but I had some different problems.
First of all I used this concrete cmake command to build with mingw from Linux: `cmake .. -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ .. -DTGUI_BACKEND=GLFW_OPENGL3 -DTGUI_SHARED_LIBS=FALSE` from a build folder I created so .. is using the root CMakeList.

I got a bunch of errors like these: `/usr/x86_64-w64-mingw32/include/c++/11.2.0/cwchar:148:11: error: ‘fwide’ has not been declared in ‘::’
  148 |   using ::fwide;
`
`/usr/x86_64-w64-mingw32/include/c++/11.2.0/bits/basic_string.h:6790:51: error: ‘vswprintf’ is not a member of ‘std’; did you mean ‘vsprintf’?
 6790 |   { return __gnu_cxx::__to_xstring<wstring>(&std::vswprintf, 4 * sizeof(int),
`
Any idea?

Apart from that, I moved from manjaro linux mingw64 to **mysys2** on Windows. This time, it compiled the static library. But it is not a real static library, when linking, the linker throw me an undefined reference error about a **__impl_XXXXXXX** symbol, which is a **dynamic** library symbol, but the library is supposed to be compiled statically. If I use the dynamic libraries all work as expected. 

When I got this error I used `nm libtgui-s.a` in order to look for the undefined symbols. Indeed, they weren't there. The symbols were static symbols without the __imp prefix. Why are the functions calling the dynamic symbol when linking with MinGW?

Linux also works fine. Is there any way to compile this statically using MinGW? Thanks in advance, such an incredible library.

In case this helps, the __impl_XXXXX undefined references were about **GLFW backends** symbols.

**Comment by texus** [comment]
I've never tried cross-compiling from linux. Those errors are weird though, they are not coming from TGUI. The TGUI code doesn't use fwide or vswprintf anywhere, so those are errors coming from the mingw headers themselves. Could you perhaps try to ~~remove the "-Wpedantic" option at https://github.com/texus/TGUI/blob/0.10/cmake/Macros.cmake#L64 and~~ replace "CXX_EXTENSIONS OFF" by "CXX_EXTENSIONS ON" at https://github.com/texus/TGUI/blob/0.10/cmake/Macros.cmake#L69?

> This time, it compiled the static library. But it is not a real static library, when linking, the linker throw me an undefined reference error about a __impl_XXXXXXX symbol, which is a dynamic library symbol, but the library is supposed to be compiled statically

Did you define TGUI_STATIC in your project? This is needed for TGUI to know that it needs to look for the static symbols instead of the dynamic ones. If you still get those __impl errors, could you give one example of such error with the full name of the function?

**Comment by texus** [comment]
I tried changing CXX_EXTENSIONS to ON which seemed to solve the errors you mentioned, but it still resulted in tons of "conflicting declaration" errors, because it finds both the mingw and linux headers. CMake also found opengl and glfw in /usr/lib and /usr/include, which means it found the linux files instead of the windows ones.

I got a step further by installing "mingw-w64-make" and "mingw-w64-cmake" from the AUR and running something like this (you can leave CXX_EXTENSIONS at OFF):
```
x86_64-w64-mingw32-cmake .. -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DTGUI_BACKEND=GLFW_OPENGL3 -DTGUI_SHARED_LIBS=FALSE -DCMAKE_MAKE_PROGRAM=x86_64-w64-mingw32-make
```

This resulted in an error that GLFW couldn't be found, which makes sense considering I only have the Linux library installed and not one that is compatible with MinGW. Changing "TGUI_BACKEND" from "GLFW_OPENGL3" to "Custom" (to try building without a backend) and then running "x86_64-w64-mingw32-make" then resulted in "libtgui-s.a" being build successfully.

If you have the correct GLFW libraries on your system then you may be able to get further with this information.

**Comment by dmg103** [comment]
That solved my problem. Thanks! Awesome
