### ISSUE TITLE
Text is not rendered in any widget

### ISSUE THREAD

**Issue by edgs1alu** [texus/TGUI#167]
Hi, I'm working on a GUISystem for a game and I've copied the example from the documentation, when I launch it can't see any text on the widgets.

This is what I get:
![Captura de pantalla de 2022-04-11 19-36-45](https://user-images.githubusercontent.com/78486240/162788878-bb008b6a-48ab-4477-894b-8af10192b754.png)

This is the code:
```c++

#include <TGUI/TGUI.hpp>
#include <TGUI/Backend/GLFW-OpenGL3.hpp>
#include <GLFW/glfw3.h>

struct GUISystem
{
	GUISystem(GLFWwindow& window)
		: gui_{&window}
		, theme_{"Game/assets/GUI/themes/BabyBlue.txt"}
		, font_{"Game/assets/Fonts/arial.ttf"}
	{
		auto label = tgui::Label::create();
		label->setRenderer(theme_.getRenderer("Label"));
		label->setText("This is a label.\nAnd these are radio buttons:");
		label->setPosition(150, 100);
		label->setTextSize(18);
		gui_.add(label);

		auto button = tgui::Button::create();
		button->setRenderer(theme_.getRenderer("Button"));
		button->setPosition(75, 70);
		button->setText("OK");
		button->getRenderer()->setFont(font_); // doesn't work
		button->setSize(100, 30);
		button->onPress([=](){
				std::cout << "button  callback" << "\n";
				});
		gui_.add(button);

		auto editBox = tgui::EditBox::create();
		editBox->setRenderer(theme_.getRenderer("EditBox"));
		editBox->setSize(200, 25);
		editBox->setTextSize(18);
		editBox->setPosition(75, 100);
		editBox->setDefaultText("Click to edit text...");
		gui_.add(editBox);

		auto chatbox = tgui::ChatBox::create();
		chatbox->setRenderer(theme_.getRenderer("ChatBox"));
		chatbox->getRenderer()->setFont(font_); // doesn't work
		chatbox->setSize(300, 100);
		chatbox->setTextSize(18);
		chatbox->setPosition(420, 310);
		chatbox->setLinesStartFromTop();
		chatbox->addLine("texus: Hey, this is TGUI!", tgui::Color::Green);
		chatbox->addLine("Me: Looks awesome! ;)", tgui::Color::Yellow);
		chatbox->addLine("texus: Thanks! :)", tgui::Color::Green);
		chatbox->addLine("Me: The widgets rock ^^", tgui::Color::Yellow);
		gui_.add(chatbox);

	}

	void update()
	{
		gui_.draw();
	}

	private:
		tgui::Gui gui_;
		tgui::Theme theme_;
		tgui::Font font_;
};
```
I've tried to set the font directlty to the widget renderer and nothing happens.

I am missing something?

**Comment by texus** [comment]
I downloaded arial.ttf, copied your code and added a main function, and the text is correctly drawn here on linux (for both widgets that use arial and widgets that use the built-in DejaVuSans font).

Which compiler are you using?
Which version of GLFW are you using?
Which FreeType version are you using?
Are you linking statically or dynamically?
Do you have the same result when adding `#include <TGUI/Backend/Renderer/OpenGL.hpp>` and `#define GLFW_INCLUDE_NONE` in front of the glfw3.h include?
Could you provide a full code example (i.e. with main function) so that I can test with exactly the same code?

**Comment by edgs1alu** [comment]
I've tried to copy the code from [Minimal code with GLFW_OPENGL3 backend tutorial](https://tgui.eu/examples/0.10/backend-glfw-opengl3/) to the main function of my project and it seems to work correctly, widgets and text are rendered, so I guess it is not a version or dependency problem.

The problem comes when I try to use the GLFWwindow from my Graphic engine in the tgui::Gui object I have in my GUISystem class.

I cannot provide a full code example as it needs all the ECS implementation from the project.

adding `#define GLFW_INCLUDE_NONE` does not seem to change anything.

any ideas ?

**Comment by texus** [comment]
There has to be some difference between the example code and what you are doing that is causing the issue, but without seeing the code I wouldn't have any idea what it could be either (and even if I had the code I would have to remove parts of it until the text appears, in order to find out where it goes wrong).

Is there a command line open when your project runs? Are there warnings being printed there? If there is a problem with the rendering then it might be printed there.

Perhaps you could start with the example code from the website and modify it bit by bit to look more like your project (e.g. start by putting the GUISystem you posted above into the example code), until the text stops being rendered.

**Comment by edgs1alu** [comment]
It was something related to our render pipeline, we have already fixed it.
thanks !!
