### ISSUE TITLE
The texture in CanvasOpenGL3 is flipped

### ISSUE THREAD

**Issue by 1Kuso4ek1** [texus/TGUI#172]
I created a CanvasOpenGL3 object (like in documentation). That's where i'm using it
```
viewport->bindFramebuffer();
glClear(GL_COLOR_BUFFER_BIT);
mainFrameBuffer->Draw(); // Drawing main framebuffer content (with post-processing)
Framebuffer::Unbind(); // glBindFramebuffer(GL_FRAMEBUFFER, 0);
```
Everything looks fine, but image in the canvas is flipped.
I tried `viewport->setScale(1, -1);`, but then canvas is not rendering at all.
So I opened [CanvasOpenGL3.cpp](https://github.com/texus/TGUI/blob/0.10/src/Backend/Renderer/OpenGL3/CanvasOpenGL3.cpp) and changed this
```
const std::array<Vertex, 4> vertices = {{
      {{0, 0}, vertexColor, {0, 0}},
      {{size.x, 0}, vertexColor, {normalizedTextureSize.x, 0}},
      {{0, size.y}, vertexColor, {0, normalizedTextureSize.y}},
      {{size.x, size.y}, vertexColor, {normalizedTextureSize.x, normalizedTextureSize.y}},
}};
```
to this
```
const std::array<Vertex, 4> vertices = {{
      {{0, 0}, vertexColor, {0, 0}},
      {{size.x, 0}, vertexColor, {normalizedTextureSize.x, 0}},
      {{0, size.y}, vertexColor, {0, -normalizedTextureSize.y}},
      {{size.x, size.y}, vertexColor, {normalizedTextureSize.x, -normalizedTextureSize.y}},
}};
```
and now the image is correct. I think it would be nice if normalizedTextureSize were multiplied by scale.

**Comment by 1Kuso4ek1** [comment]
Alright, today I tried some stuff and now `viewport->setScale(1, -1);` is working. I tried use it with origin parameter, but it didn't help. Then I figured out that canvas isn't rendering when it's touching bounds of `tgui::ChildWindow` (but I'm not entirely sure if it's true). Anyway, I fixed it with `viewport->setPosition({ 0, viewport->getSize().y });`

**Comment by texus** [comment]
I didn't have time when I received the notification 2 days ago and I forgot about this issue afterwards.
I've reproduced it here and I'm going to invert the y position in the Canvas class (in the vertices array like you showed).

While testing I noticed another "issue" with the canvas. The viewport is still related to the window and not to the canvas. I feel like in order to be correct I should call `glViewport(0, 0, canvasWidth, canvasHeight);` inside `viewport->bindFramebuffer()`. Unfortunately there seems to be no way to automatically undo this, so I can choose between either not calling glViewport (like now) and have potentially unexpected scaling, or call glViewport and risk breaking scaling for anything you render afterwards. So for now I'll just leave it.
