### ISSUE TITLE
Night build: error LNK2038: mismatch 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug'

### ISSUE THREAD

**Issue by dezmen3** [texus/TGUI#180]
Hello, I'm trying to compile simple example using TGUI 1.0 build from TGUI-1.0-nightly-VisualStudio-32bit-for-SFML-2.5.1.zip pack, but getting errors while using static linking, 1.0 versions gives me MDd_DynamicDebug errors:

`
1>tgui-s-d.lib(unity_batch-5_cxx.obj) : error LNK2038: mismatch detected for RuntimeLibrary: value MDd_DynamicDebug doesnt match value MTd_StaticDebug in launcher.obj

1>tgui-s-d.lib(unity_WINDOW_BACKEND_SFML_cxx.obj) : error LNK2038: mismatch detected for RuntimeLibrary: value MDd_DynamicDebug doesnt match value MTd_StaticDebug in launcher.obj

1>tgui-s-d.lib(SFML-Graphics.obj) : error LNK2038: mismatch detected for RuntimeLibrary: value MDd_DynamicDebug doesnt match value MTd_StaticDebug in launcher.obj
`
etc...

SFML 2.5.1 itself running fine. I'm using VS2022, x86 debug settings, Runtime Library: Multi-threaded Debug (/MTd), Preprocessor: TGUI_STATIC;SFML_STATIC; and Input libs:
`User32.lib;
Advapi32.lib;
opengl32.lib;
winmm.lib;gdi32.lib;
flac.lib;
vorbisenc.lib;
vorbisfile.lib;
vorbis.lib;
ogg.lib;
ws2_32.lib;
sfml-graphics-s-d.lib;
sfml-window-s-d.lib;
sfml-system-s-d.lib;
sfml-audio-s-d.lib;
sfml-network-s-d.lib;
tgui-s-d.lib;
`

**Comment by texus** [comment]
The precompiled TGUI libraries on the website were all build with /MD (because this is the default in Visual Studio), and are incompatible with your /MT setting.

If you want to build your project with /MT then you will have to build TGUI yourself with cmake (tutorial: https://tgui.eu/tutorials/1.0/cmake/) and make sure you set TGUI_USE_STATIC_STD_LIBS to ON (as this is the setting that chooses between /MD or /MT).

**Comment by dezmen3** [comment]
Sadly, tried to compile TGUI but have issues after compiling SFML, TGUI can't find SFML dependencies in cmake gui, for example Freetype

**Comment by texus** [comment]
What are you specifying as value for `SFML_DIR`?
The place where SFML was installed to, the folder in which you built SFML or the root folder of the SFML source code? (The first two options should work, the third option would not)

**Comment by texus** [comment]
I tried it here and it does seem to have an issue with FreeType when linking statically and setting `SFML_DIR` to the build directory instead of installing SFML and setting `SFML_DIR` to lib/cmake/SFML directory of the installed files.

When it failed, it should have added a FreeType_LIB variable in CMake that is set to `FreeType_LIB-NOTFOUND`.
You need to change this value to `YOUR_SFML_DIRECTORY/extlibs/libs-msvc-universal/x86/freetype.lib`. You probably also need to fill in SFML_DIR again as it might have been reset when giving the FreeType error.

Afterwards there should be no more errors and you should be able to build TGUI.

**Comment by texus** [comment]
Do you still need TGUI libraries compiled with /MT?
Because if you still need them and don't manage to build them then I can build them for you.
Otherwise this issue can be closed.

**Comment by dezmen3** [comment]
> Do you still need TGUI libraries compiled with /MT? Because if you still need them and don't manage to build them then I can build them for you. Otherwise this issue can be closed.

Yeah, if you can. I think it will be useful for others too, Packing everything in one exe is always good :)

**Comment by texus** [comment]
You can download the version from https://www.dropbox.com/s/s2b71xi44ihv7v9/TGUI-1.0-dev-a4cd5a65-VS2022-x86-MT.zip?dl=1

Note 1: The download includes SFML libraries as well, you have to use them. The SFML version in your project has to always match exactly with the SFML version used to build TGUI. (This is why I don't typically create /MT libraries, there are no SFML libraries I can reference to so I would need to build and attach them myself)

Note 2: The TGUI library was build with c++17, so you will need to set the C++ Language Standard to at least "/std:c++17" in your project.
