### ISSUE TITLE
How to build from source on MSYS2?

### ISSUE THREAD

**Issue by ghost** [texus/TGUI#185]
I'm using the MINGW64 environment.

**Comment by texus** [comment]
TGUI officially doesn't support MSYS2 yet, but I've just done some testing and made a patch to the cmake script that should make it work.

I'm assuming you have the following installed: mingw-w64-ucrt-x86_64-gcc (or similar), mingw-w64-x86_64-cmake, make and git.

Start by downloading TGUI if you haven't already (and if you already did then make sure to update it to the latest version):
```c++
git clone https://github.com/texus/TGUI
```

Run cmake with the `-S` parameter being the downloaded TGUI folder and `-B` a new directory in which temporary files will be written. I'm setting TGUI_BACKEND to Custom here because I don't know what you will be using and this command will simply build TGUI without any backend. You will need to take a look at https://tgui.eu/tutorials/1.0/cmake/ for the other options that you can pass to CMake.
```c++
/mingw64/bin/cmake -S TGUI -B TGUI-build -G "Unix Makefiles" -DTGUI_BACKEND=Custom
```

Then enter the build directory and run make (optionally with an amound of threads to use) to build the TGUI library.
```c++
cd TGUI-build
make -j8
```

If you passed an install location with `-DCMAKE_INSTALL_PREFIX=...` as parameter to cmake earlier then you can then run `make install` to install the libraries there.

Let me know if you encounter any issues.
