### ISSUE TITLE
Why different code for each backend?

### ISSUE THREAD

**Issue by ghost** [texus/TGUI#186]
Code is different for each backend (https://tgui.eu/examples/1.0/). Why can't I use the same code for different backends?

**Comment by texus** [comment]
Almost all code is independent from the backend, only the creation of the gui and passing the window events to it will need different code. This is because TGUI just provides the UI but doesn't handle window creation and related things like getting the events from the window.

Normally you would already be using SFML, SDL or GLFW in your own code, then you simply select the backend based on what you were already using.
