### ISSUE TITLE
Vulkan backend

### ISSUE THREAD

**Issue by ghost** [texus/TGUI#189]
Nowadays it's all about Vulkan. MSYS2 also has the package `mingw-w64-x86_64-vulkan-devel`.

**Comment by texus** [comment]
I won't implement this myself. If someone needs it and writes it themselves, then I'd happily merge the code into TGUI, but I won't spend time on this.

99% of TGUI users are using the SFML_GRAPHICS backend (because TGUI started out as library for SFML), so I won't spend a large amount of work into writing a backend which someone might want in the future.
