### ISSUE TITLE
BackendRenderTarget.drawRoundedRectangle and HighDPI

### ISSUE THREAD

**Issue by RGPaul** [texus/TGUI#196]
Hi texus,

does the BackendRenderTarget.drawRoundedRectangle function considers High DPI? It seems to me that it's not.

**Comment by texus** [comment]
As far as I can tell the border is drawn at the correct size when using high dpi.
However, because because the corners are drawn with small triangles and there is no anti-aliasing happening, they look terrible even without high-dpi scaling.

So unless you are talking about something other than the output looking pixelated, I don't think there is much that I can do about it. You are better off using a background texture for the button, so that the rounded borders can be anti-aliased.

**Comment by RGPaul** [comment]
Ah yeah - the size is correct, the corners just look pixelated.
I will use a background texture with rounded corners.

Thanks
