### ISSUE TITLE
A Few SubwidgetContainer Issues

### ISSUE THREAD

**Issue by CasualYT31** [texus/TGUI#209]
I've been running into quite a lot of problems surrounding `SubwigetContainer` widgets recently and most of them are caused by the fact that the internal `SubwidgetContainer`'s `Container` is not attached to the `Container` that the `SubwidgetContainer` itself is in. This is by design, though, and I'd imagine changing that will cause a lot of problems for code that relies on `SubwidgetContainer` not itself being a `Container`. Just mentioning this since the issues I'm going to bring up are caused by this design decision.

1. If you set the focus to a widget within a `SubwidgetContainer` using `setFocused(true)`, it won't receive key press events and such, because the `SubwidgetContainer` isn't registered as having the set focus automatically (unless the mouse was used to set the focus, then it will work as normal).

One of the ways you could fix this is by registering signal handlers with `SubwidgetContainer::m_container`, so that when its focus state changes, it can be changed accordingly in the `SubwidgetContainer` itself. Typically the user wouldn't register their own signal handlers with the internal container when working with a `SubwidgetContainer`, but I'm still not sure about this approach...

I will likely end up doing this in my own fork but if this solution does sound good to you, I can create a PR for it.

2. Using `getAbsolutePosition()` on a widget that is within a `SubwidgetContainer` will end up computing the position of the widget relative to the `SubwidgetContainer`, since its `Container` has no parents.

Really not sure how best to fix that from within TGUI...

3. It is trickier to traverse up the widget hierarchy from a widget within a `SubwidgetContainer`, you might expect that using `getParent()` on a widget within the `SubwidgetContainer` will eventually return the `SubwidgetContainer` but it won't, since they are detached.

Not sure if that should be "fixed", it's the correct behaviour but it's not very intuitive.

There will be more issues, but I'm not privy to them yet. I may have also forgotten some problems that I've had to mitigate against in my own code 😅.

**Comment by CasualYT31** [comment]
> I'd imagine changing that will cause a lot of problems for code that relies on SubwidgetContainer not itself being a Container

I had originally thought about making `SubwidgetContainer` inherit from `Container`, but I guess another thing you could do is set the parent of the container to the `SubwidgetContainer`'s parent. That would solve a few problems but not sure if this would introduce other issues.

**Comment by texus** [comment]
If you need complicated things like controlling focus or accessing the absolute position, then you probably shouldn't be using SubwidgetContainer. As far as the gui is concerned, a SubwidgetContainer is the leaf widget, so calling getAbsolutePosition on something inside it doesn't make sense. In fact, outside the custom widget code itself, you probably shouldn't even be accessing the subwidgets.

SubwidgetContainer made it easier to write something that combines several widgets without having to write the glue code to put it all together (which you would need if you inherit from Widget) and without exposing the subwidgets (like you get when inheriting Container). Unfortunately, in practice such widgets don't work very well out of the box once you start doing more complex things.

If you don't care about exposing the Container functions, then your custom widget should inherit from Container, not SubwidgetContainer.

The two existing TGUI widgets that inherit from SubwidgetContainer (TabContainer and SpinControl) were both contributed, I never wrote any widgets using SubwidgetContainer myself.
- SpinContol is a widget that I believe applies SubwidgetContainer correctly: it consists of two subwidgets which aren't exposed. There is no way for you to call setFocus or getAbsolutePosition on the children.
- TabContainer on the other hand probably shouldn't inherit from SubwidgetContainer, as it exposes too much of its internal widgets. I think this might be a point of frustration, as you might expect widgets that are added on a TabContainer panel to actually work like regular widgets.

So if the problems you are facing with SubwidgetContainer are related to TabContainer, then maybe we should change the way that widget works. If the problems are related to a custom widget from you then you might want to consider inheriting from Container instead of SubwidgetContainer.

I'm definitely open for debate on how SubwidgetContainer works and how it can be improved, but before we start looking for solutions to the issues you raised in your first post, I first need to understand how you are trying to use SubwidgetContainer exactly.

**Comment by CasualYT31** [comment]
Thanks for your response! I should clarify how I'm using `SubwidgetContainer` currently.

I haven't tried using `SpinControl` yet, I will be doing so later on. But after reading your response I am realising that my problems are down to `TabContainer` and perhaps not to `SubwidgetContainer`.

Right now, I'm using a `TabContainer` as a basic text editor. Each tab represents one file, and each panel contains a `TextArea` that the user can type in.

When a tab is selected by the user, I want to be able to set the focus of the `TextArea` so they can begin typing immediately. Unfortunately, since the `Container` the `Panel` is in has no parent, it won't propagate out to `TabContainer`, so right now I'm having to manually set the focus of the `TabContainer`, too. This is doable but not very convenient because I don't have direct access to the `TabContainer` when I set the `TextArea` to have focus.

This is part of a script editor within a game engine. One feature that's in the engine is to let the user select different widgets using the arrow keys, and to highlight selected widgets using square bracket sprites. Currently, I use `getAbsolutePosition()` to know where to draw the sprites so that they match up with the location of the widget. I do not do this right now, but it might happen that in the future, I'd want the user to select a widget within a `SubwidgetContainer`, and I'd need an accurate `getAbsolutePosition()` for that. I have written a workaround in my game engine for this case, though.

I do agree that `SpinControl` being a `SubwidgetContainer` makes a lot more sense, since you would never really need to interact with the individual widgets that make it up programmatically. But I do feel like `TabContainer` being a `SubwidgetContainer` is a bit of a hindrance since it otherwise "acts" like a regular container, and you can add widgets to it, which IMO goes against the idea of encapsulating multiple widgets into one.

How one would go about changing it, though, I'm not too sure. Whilst the `Panel`s it creates are completely exposed, you would not really want to expose the `Tabs`, or remove individual tabs without removing their `Panel`s, or vice versa. So I can see why `SubwidgetContainer` was employed, but it probably introduces more issues than it resolves.

In any case, any rework would require a lot of effort. For my purposes, I can probably just make some "dodgy" edits to those classes, and not make PRs of them. Thanks again, your library is brilliant!

**Comment by texus** [comment]
I've decided to let TabContainer inherit directly from Container. Doing so has it's downsides, but I do think it outweighs the downsides of letting TabContainer inherit from SubwidgetContainer.

The `Tabs` of the TabContainer were already exposed via the `getTabs()` function. You could already shoot your own foot off, inheriting from Container just makes it a little easier. It's going to be a bit weird that TabContainer now has a public `add()` function which you should not be using though.

Maybe I'll look for a cleaner solution in the future, but in the past I've only made fixes to the TabContainer class when I really needed to, so somehow I don't think this situation is going to be improved anytime soon.
