### ISSUE TITLE
Black background shown when changing window size

### ISSUE THREAD

**Issue by xland** [texus/TGUI#220]
OS : Win 10
TGUI : latest version with sfml 3.0
When changing window size(smaller to bigger),
the window show black background.
I found that SFML only has event `sf::Event::Resized`, but not event `sf::Event::Resizing`

![image](https://github.com/texus/TGUI/assets/2980915/c0ebcf48-01fd-45c2-a846-f9a7eda9cda0)

**Comment by texus** [comment]
This is a known issue in SFML.

Windows will keeps sending resize events to the SFML window, which SFML translates to sf::Event::Resized events. During a resize, your code will remain stuck in the window.pollEvent() loop because it keeps returning true because there is always an sf::Event::Resized event available. Your code thus never reaches the window.clear() and window.display() lines until the resize is finished.

See https://en.sfml-dev.org/forums/index.php?topic=29181.msg180279#msg180279 which also links to a potential workaround.

**Comment by xland** [comment]
Thanks very much

**Comment by xland** [comment]
Does SDL backend have the same issue?
@texus

**Comment by texus** [comment]
I've never tested that with the SDL backend, but I found https://github.com/libsdl-org/SDL/issues/1059 which suggests that by default it will have the same issue.

However, that SDL issue was closed in SDL 2.30, where you can apparently check for `if (event->type == SDL_WINDOWEVENT && event->window.event == SDL_WINDOWEVENT_EXPOSED)` in your event loop to detect that the window is being resized (or moved). So you would still need to change your code to solve the issue, but there would be a solution where you call your drawing code both from the main loop if there are no events left, and when you receive SDL_WINDOWEVENT_EXPOSED inside your event loop.
