### ISSUE TITLE
Hover style does not disappear when mouse moves out of the window

### ISSUE THREAD

**Issue by xland** [texus/TGUI#223]
OS : Windows 10
TGUI : Latest version sfml backend

Hover style does not disappear when mouse moves out of the window

![image](https://github.com/texus/TGUI/assets/2980915/5f570850-e32c-4e02-9cf5-7c8bef8f6552)

Some code that might be useful for windows
```c++
case WM_MOUSEMOVE: {
      if (!mouseTracing)
      {
          TRACKMOUSEEVENT tme = {};
          tme.cbSize = sizeof(TRACKMOUSEEVENT);
          tme.dwFlags = TME_LEAVE;
          tme.hwndTrack = hWnd;
          mouseTracing = TrackMouseEvent(&tme);
      }
      //....
      break;
}
case WM_MOUSELEAVE:{
      mouseTracing = false;
      //...remove hover style
      break;
}
```
https://github.com/texus/TGUI/issues/221#issuecomment-1754159207

**Comment by texus** [comment]
If you are talking about the hover state of the close button, then this has nothing to do with TGUI. The TGUI library only renders in the client area of the window and has no access to borders or title bar.

If you mean that some TGUI widget remains in hover state after the mouse leaves the window then this is because of a limitation of the event handling. SFML doesn't provide any event to inform TGUI that the mouse is no longer on top of the window.
You could fix that by manually updating the hover state when receiving the WM_MOUSELEAVE event with the following code:
```c++
for (auto& child : gui.getWidgets())
    child->mouseNoLongerOnWidget();
```

**Comment by xland** [comment]
Thanks very much.

**Comment by xland** [comment]
Thanks very much.

That close button is a button widget rendered by TGUI.
I found that after calling `mouseNoLongerOnWidget` method, TGUI executes the following code internally.
But my widget remains in hover state.
```c++
    void Widget::mouseLeftWidget()
    {
        if (m_parentGui && m_parent && (m_parent->getMouseCursor() != m_mouseCursor))
            m_parentGui->requestMouseCursor(m_parent->getMouseCursor());
       //m_mouseHover from true to false
        m_mouseHover = false;
        onMouseLeave.emit(this);
    }


    void ButtonBase::updateState()
    {
        const auto newState = priv::dev::getStateFromFlags(m_mouseHover, m_down, m_focused, m_enabled);
        if (m_state == newState)
            return;
        //The following code has been executed
        m_state = newState;
        m_backgroundComponent->setComponentState(m_state);
        m_textComponent->setComponentState(m_state);
    }
```

![image](https://github.com/texus/TGUI/assets/2980915/3284fa44-0ad6-4d1b-bcdc-d0978e1c3d82)

![image](https://github.com/texus/TGUI/assets/2980915/3bdfc002-badd-43d2-a091-bee7fc6f988e)

**Comment by texus** [comment]
The issue seems to be that `gui.mainLoop()` doesn't redraw the window when this happens.

The mainLoop() function will redraw the screen whenever it receives an event, or when a timer expires. Because this event only happens in your WndProc and doesn't happen via SFML, the mainLoop() function doesn't know about it and it doesn't refresh the window.

There are 2 solutions for this:
1) Force the window to refresh after calling mouseNoLongerOnWidget.
This can be done by adding `tgui::Timer::scheduleCallback([]{});` to the end of your WM_MOUSELEAVE code. This will schedule a timer event that gets executed as soon as possible, after which the mainLoop() function will redraw the screen.

2) Don't use the mainLoop() function.
You can have your own main loop where you can decide for yourself when to refresh the screen. The code needed for this can be found in the "Main loop" section of [tgui.eu/tutorials/latest-stable/backend-sfml-graphics/](https://tgui.eu/tutorials/latest-stable/backend-sfml-graphics/#main-loop).
Note that unlike the mainLoop() function, that code from the tutorial will constantly redraw the window, so you may want to somehow limit the amount of time spend on refreshing the screen (e.g. with `sfmlWindow.setFramerateLimit(30)`)

**Comment by xland** [comment]
Thanks.

Final code for anyone else who sees this session.
```c++
static bool mouseTracing{false};
static void mouseOutWindowCasecade(tgui::Widget* target) {
    if (target->isContainer()) {
        auto container = (tgui::Container*)target;
        for (auto& child : container->getWidgets()) {
            mouseOutWindowCasecade(child.get());
        }
    }
    else
    {
        target->mouseNoLongerOnWidget();
    }
}
static void mouseOutWindow(const HWND& hwnd) {
    auto win = WindowBase::wndMap[hwnd];        
    for (auto& child : win->gui->getWidgets()) {
        mouseOutWindowCasecade(child.get());
    }
}
```

```c++
case WM_MOUSEMOVE: {
    if (!mouseTracing)
    {
        TRACKMOUSEEVENT tme = {};
        tme.cbSize = sizeof(TRACKMOUSEEVENT);
        tme.dwFlags = TME_LEAVE;
        tme.hwndTrack = hwnd;
        mouseTracing = TrackMouseEvent(&tme);
    }
    break;
}
case WM_MOUSELEAVE: {
    mouseTracing = false;
    mouseOutWindow(hwnd);
    tgui::Timer::scheduleCallback([] {});
    break;
}
```

**Comment by texus** [comment]
After looking into this further, it turns out that I do receive an event when the mouse leaves the window.
So this can in fact be considered a bug in TGUI.

It has been fixed now, if you use the latest version then you won't need your workaround anymore. When the mouse leaves the window, the hover state will now be reset and the window contents will be redrawn.

**Comment by xland** [comment]
I tested the latest code of TGUI.
It works fine.
