### ISSUE TITLE
On macOS, Input Method Editors(IME) behavior seems incorrect.

### ISSUE THREAD

**Issue by TakWolf** [texus/TGUI#230]
I current use: `set(TGUI_BACKEND SFML_GRAPHICS)`

On Windows, it is OK.

But, on macOS, The position of the IME floating window is incorrect, and its content will not be output to the EditBox.

**Comment by TakWolf** [comment]
I found this: https://github.com/texus/TGUI/issues/219#issuecomment-1722325914

Does this mean that it is currently not supported on macOS and Linux

**Comment by texus** [comment]
SFML has no support for the IME, so I added some Windows-specific code to TGUI in order to position it correctly on Windows. As you noticed, there is no support for it on Linux and macOS (at least not with the SFML backend, the SDL backends might support it because SDL does support the IME directly without code in TGUI).

I can try adding an implementation for macOS as well.

How does the IME work on macOS? Is this something that the OS has open the whole time and I just need to update its position? Can you link me to a guide on setting up the IME on macOS so that I can try experimenting with it here?

**Comment by texus** [comment]
I've tried to find information of how to move the position of the IME window on macOS and it seems like I won't be able to do it.

I looked at the source code for SDL, GLFW and ImGui, and they all have a class that inherits from `NSView<NSTextInputClient>` where they implement the `firstRectForCharacterRange` function to choose the location where the text is being typed (which would determine the position of the IME floating window).

Unfortunately that NSTextInputClient class also handles all other key input logic. So unlike on Windows, it's not possible to just move the window without altering anything else on macOS. So the logic really needs to be implemented in the backend itself and TGUI can't update the position if the backend doesn't support setting a position.

This will thus remain unsupported on macOS with the SFML_GRAPHICS backend as long as SFML provides no way to set a text input rectangle like SDL does.

**Comment by TakWolf** [comment]
I am not an expert in this field. 

But I found that SFML does have some work related to IME

https://github.com/SFML/SFML/issues?q=ime

I can't see the current progress, but I will try to do some research

**Comment by TakWolf** [comment]
I tried switching backend  to `SDL_RENDERER` with SDL3 (the master branch), everything is working well.
(On windows should add `SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1")`, see: https://discourse.libsdl.org/t/sdl-2-0-18-released/33768)

This is indeed an issue with SLFM. Overall, SDL is indeed better than SLFM.
I'm not sure if I should keep the issue open.

**Comment by texus** [comment]
I'll close the issue, as there isn't really anything that I can do in TGUI to improve the situation
