### ISSUE TITLE
[Bug] Dead radio button text

### ISSUE THREAD

**Issue by lpogic** [texus/TGUI#233]
Hello, radio button text may become unclickable or partially clickable if a change is made after previously being added to a container:

```
  auto grid = tgui::Grid::create();
  auto chb = tgui::CheckBox::create("Clickable part");
  grid->add(chb);
  grid->addWidget(chb, 0, 0);
  chb->setText("Clickable part Unclickable part");
  gui.add(grid);
```

**Comment by texus** [comment]
While this is definitely wrong behavior, I'm not sure this is fixable.
This is a limitation of the Grid widget, it doesn't realize that the radio button changed size so it won't update the column width.
You would have to call `grid->setWidgetCell(chb, 0, 0);` to force the grid to update the cell.

Edit: I'll let the setText trigger an onSizeChange callback (even though the actual size returned by getSize doesn't change as it excludes the text). That should automatically trigger an update.

Edit 2: You shouldn't call both `add` and `addWidget`. Either call only `addWidget`, or call both `add` and `setWidgetCell`. Your code currently prints a warning to stderr and may stop functioning in the future.

**Comment by lpogic** [comment]
Re: Edit 2: You're right, I forgot to delete `grid->add(chb);`.

Do you think adding the onFullSizeChange signal would be overkill?

**Comment by texus** [comment]
It's something that could be considered in the future. However the whole FullSize thing has always been a bit of a hack that I needed once I realized that there are a handful of exceptional widgets that need to be bigger than their size. I'm sure there are other places in the code that won't work properly with such widgets because of Size==FullSize assumptions being made.
