### ISSUE TITLE
CheckBox button stretched when used in a vertical layout

### ISSUE THREAD

**Issue by rasoolZero** [texus/TGUI#244]
Probably related to #243 

```C++
	clearAnimation = tgui::CheckBox::create("Clear");
	auto vl5 = tgui::VerticalLayout::create();
	vl5->add(clearAnimation);
	vl5->addSpace(10.f);
```
![image](https://github.com/user-attachments/assets/8cc5711e-2a3d-4df8-8fd4-9af78a82c86f)
as shown in the image (last column), the checkbox button is stretched to fill the whole space based on the width of vl5

**Comment by texus** [comment]
You shouldn't use RadioButton or CheckBox in a VerticalLayout, it's just not supported. I'm honestly surprised the results are this good, I would have expected the text to be rendered completely outside the layout (and thus not visible as it would be clipped). Apparently a modification that I once made to keep the thumb of a slider inside the layout has resulted in the check mark becoming small enough for the text to fit next to it.

While VerticalLayout sounds like it would be the right tool for the job, it really only exists for simple widgets like buttons and edit boxes that are perfectly rectangular. VerticalLayout doesn't just places widgets next to each other, but it also takes control of their size. The size of the CheckBox and RadioButton are just the check mark, not the text next to it, which is why the check mark tries to fill as much space as possible. The gap between the RadioButton and its text is because internally it's width is stretched like the CheckBox but when rendering it only draws a circle with diameter `min(width, height)`.

TGUI has only limited support for automatic layouts. While there are many different methods ([setPosition/setSize](https://tgui.eu/tutorials/latest-stable/layouts/) layouts, [AutoLayout](https://tgui.eu/tutorials/latest-stable/layouts/#autolayout) for containers, and widgets like VerticalLayout and Grid), every method has its caveats.

For your use case you might be able to use the [Grid](https://tgui.eu/tutorials/latest-stable/widgets-overview/#Grid) widget, which  only positions its child widgets instead of also resizing them like VerticalLayout does.

**Comment by rasoolZero** [comment]
Oh I see.
I fixed the whole thing using Grids, thanks for your advice and your work, much appreciated.
