### ISSUE TITLE
Runtime Error in sample apps (for GLFW_OPENGL3 backend)

### ISSUE THREAD

**Issue by NayLinDev** [texus/TGUI#247]
Hi,
I compiled TGUI v1.6 with GLFW_OPENGL3  backend (GLFW 3.4 and freetype-windows-binaries-2.13.3), all of TGUI lib with dll, gui-builder and two sample are compiled successfully). gui-builder runs perfectly.

But in two sample app, an exception is thrown at `BackendRendererOpenGL3.cpp`, at the function `BackendRendererOpenGL3::BackendRendererOpenGL3(ContextLoadFuncType contextLoadFunction)`,  at the line 
`if (version == 0)
  throw Exception{U"BackendRendererOpenGL failed to query OpenGL version, or requested OpenGL version wasn't supported. Has an OpenGL context been created yet?"};`.

What could possibly get wrong?

Thanks

**Comment by texus** [comment]
I can't reproduce this with the same TGUI, GLFW and FreeType versions and it didn't make any sense that the gui-builder would work but the examples wouldn't. It took me a while to come up with a potential explanation, but **are you perhaps using a static GLFW library?** That is the only case that I can think of that could cause such weird behavior.

If you link TGUI dynamically (i.e. using a dll) then you should also link to a dynamic GLFW library (actually all public dependencies should be dynamic, which are both GLFW and FreeType in this case). If you link TGUI statically then it doesn't matter whether the dependencies is static or dynamic.

If the TGUI dll links to GLFW statically, then some of the GLFW library may be duplicated inside the dll (the same code/memory will also exist in your program when you link to GLFW). That could cause weird behavior as your initialization only changes the code that is linked in your program while TGUI will access the uninitialized code that is linked inside the dll. The gui-builder is special because it doesn't use GLFW directly and the only GLFW code is inside the TGUI dll (so even if it's GLFW stuff is duplicated, it only touches one version of it).

I should probably figure out a better way to let CMake give an error in that case. There is actually an error that occurs when I detect a static GLFW library when creating a dynamic TGUI library, but only when GLFW is found using glfw3_DIR and not when using GLFW_INCLUDE_DIR and GLFW_LIBRARY (because there is no information about what type the library has in that case).

**Comment by NayLinDev** [comment]
Thanks.
Yes, I did pointed the `GLFW_LIBRARY` to the static library, which is `glfw3.lib`. I will try again with link to `glfw3dll.lib`.

After recompiling it with `GLFW_LIBRARY` pointing to `glfw3dll.lib`, the two examples and gui builder all run properly. Thanks again.
