### ISSUE TITLE
New (?) compile errors with VS2013

### ISSUE THREAD

**Issue by TheWehe** [texus/TGUI#36]
I think they are all template-related. Do you already know about them? 
I'm asking because it seems like you already have/had problems with VS2013 (ListBox.cpp Line 64/65).

**Comment by texus** [comment]
Could you perhaps post the errors?

Do you have the latest update of VS2013 installed?

**Comment by TheWehe** [comment]
Oh, that could be the problem. After installation I'll try again.

**Comment by TheWehe** [comment]
Yees. I'm sorry. It works now.
There's only the warning concerning the old C-functions but that's not important I think.

**Comment by texus** [comment]
I'm glad to hear that updating to the latest version solves it. At least I now know for sure that it is what I should recommend when people can't build it in VS2013. You are the second person in short time who got these errors while I never had these errors even though I didn't have the latest VS2013 version. I guess you must have had an even older one.

The warning is indeed not important for using tgui, but it does make me wonder. What warning are you talking about exactly? There has always been an annoying warning about strcpy, but it was supposed to be fixed two weeks ago.

**Comment by TheWehe** [comment]
I don't know the exact name right now, but it's something like you have to define "CRT Secure No Warnings" to disable it. Normally if I use those functions I get the warning as error, so it stops compiling. Therefore I think you regulated the debugging level or something instead of defining CRT... because VS generated only a warning. That's the only fitting explanation for me. 

Excuse me for my school English. I don't have much experience using it practically :P

**Comment by texus** [comment]
I have no idea why the warning still pops up (since it is supposed to use the secure function https://github.com/texus/TGUI/blob/v0.7-dev/src/TGUI/Clipboard.cpp#L86-L90).

But your description matches with what I have noticed before. It is frustrating that it gives a compile error on the code without the right compiler settings, because the reason I use that code in the first place is because the Windows API itself is so damn low level. And the secure functions that they recommend only exist in VS.

In the examples on msdn they seem to use memcpy instead of strcpy, which would also solve the warning/error. But it doesn't really matter, with some luck the clipboard will be handled by sfml soon.

Since the errors are solved with updating VS and I'm no longer going to look any closer at the warning, I guess I'll just close this issue. Thanks anyway.

**Comment by TheWehe** [comment]
Doesn't appear anymore. Just don't ask, I have no plan :D
