### ISSUE TITLE
Form Builder

### ISSUE THREAD

**Issue by AustinHaugerud** [texus/TGUI#45]
I think a form builder would be highly beneficial for use with TGUI. While for some projects hardcoding is fine, TGUI is also just as viable a choice for projects with large UI's with its robust and modern C++ design, making for hardcoding to become and more painful. 

  A form builder for v0.7 should at minimum have support for the original features of v0.6 (excluding deprecated parts of the API). 

  Due to the fact that v0.7 adds some significant new concepts and features, the form builder should likely reflect this. For example, the more advanced scaling and layout features. 

  I'd like to for this to be a discussion about what features should be in a v0.7 form builder.

**Comment by texus** [comment]
There have been two major versions of the form builder (v0.2 and v0.6) each having their own small problems which should be avoided. The first version had every property hardcoded for each widget causing a lot of work to make small changes. Hardcoding the properties will still be required because some function has to be called when the value is changed and which function this is can't be loaded from a text file. But the program itself should be more modular than the first form builder which was full of duplicate code. The second form builder was way simpler, I had added setProperty and getProperty functions to TGUI and the form builder just had to pass the string values to and from TGUI. The form builder itself did not check the input and couldn't even do it because it has no idea on how the value should look. Although it was extremely dynamic I realized that this wasn't a good idea, e.g. adding a color picker was not possible in a clean way since the form builder did not know which properties were colors. The setProperty and getProperty functions in v0.7 should probably not be used as they cannot access all properties.

One major thing that the form builder lacked was hierarchy. It should be possible to create panels and child windows and place widgets in them (panels are needed for radio button groups).

Loading a widget file should also be simpler, you shouldn't have to create a new form and then load it, it should be possible to immediately load a file when you start the form builder.

A color picker would be a nice addition for when having to set a color property.

I'm not sure how the layout system could be integrated, but it would be nice to be able to use it to set relative sizes and positions somehow.

A really cool feature would be to align widgets, e.g. if a button has x coordinate 45 then when moving a button below it the x position should jump to 45 instead of e.g. moving per 10 pixels. But I wouldn't even know where to start for implementing that, it could get difficult to predict the position when there are multiple widgets around.

There is one major rewrite that I am currently considering that will influence the form builder code. Right now every widget has a renderer which has setters but it doesn't has getters to access the values. The getPropery function could however be used in the meantime to get access to them indirectly. These renderers were added only for one reason: I wanted to keep the API of the widget itself more clean and move customization code in a different class. However I have noticed that this design led to some more difficult internal code. The widget constantly needs access to the renderer and vice versa, it would be easier if they were in the same class. So I am currently thinking of moving everything from the renderers back into the widget classes themselves and in this process I would immediately add getters. But this is a big task and I have little time so this won't happen soon. If the form builder gets written before this change is made then it should use the getProperty function from the renderer for now and be refactored later.

**Comment by AustinHaugerud** [comment]
Most of these ideas I agree with. Things like the lack of hierarchy wasn't a killer, but it would be much more convenient.

Concerning the rewrite of remerging the renderer components into the widgets, I myself have liked the separation from the user's perspective. I understand if it has added too much internal complexity, but throwing in my two cents, I find it's quite nice in the public API. It allows developers to do things like use a factory pattern for renderers which makes it easy to create multiple color schemes for UI's that a user could select from. I personally really like the component pattern however, so I'm biased and I'm sure some would disagree with me. 


I think making use of things like layout scaling and panels in the form builder is possible, but the the program will have to treat it hierarchically just as it will with child windows for example. 

With your idea for being able to just open the form builder and immediately load the UI you were last working on, I think to do this in a way that won't confuse the user there will be a need to add the concept of projects. Then you'd have some pseudo layout like

[root]
MenuBar
[ChildWindow] // sub UI
   Button
   Label
[/ChildWindow] // sub UI

[SomeOtherChilWindow]
  // repeate
[/SomeOtherChildWindow]
[/root]

Then you toggle whether or not to show these sub UI's easily. This might also complicate the loading process the user wants in their program however. They might not want to load all of the sub UI's, so it might be important to make sure the sub ui's are saved separately from the root.

**Comment by texus** [comment]
The problem with the renderers are that it is hard to define what belongs where. Label for example has two kind of uses, if you want a label with a background and borders and word-wrap then the idea of a renderer is fine. But if you just want some text on your screen then it is stupid to having to access a renderer just to set the text color. Labels are used a lot internally and it bothered me so much that I ended up giving Label a setTextColor function as well, so now there are two methods to do the exact same thing, one in the renderer and one in the label.

With the separate renderer class I hoped that the renderer could be separated from the logic part, it would define how the widget looks, it would be replaceable (e.g. a renderer for textured widgets, one for colored widgets and the ability to create custom renderers). It is only now, after it is written that I realize that none of these things are possible. The widgets and the renderers need to share way to much information.

> makes it easy to create multiple color schemes for UI's that a user could select from
Is this something you assume or something that you have tried? I think you might overestimate what you can do with the renderers, they are purely there to keep the functions out of the API of the widget, the renderer classes themselves have very little use. I would love to separate them more from the widgets to have a more modular structure, but I didn't find any good way to achieve this.

I  wasn't really talking about immediately opening the thing you were last working on when you open the form builder, but having something like recent projects/files sounds nice. I was actually talking about a complain that I got once or twice that when you start the form builder you first have to create a new form, give it the same size and filename as last time and then you had to click load (and if you miss-click like I once did and you hit save instead then you lost everything). There should be a load option in the menu bar from the beginning (or anywhere else in case the menu bar is replaced by some start screen).

How projects are handles and how the sub UIs are stored doesn't matter much to me, anything that works is fine. But the widget files should have the same layout/syntax as they currently have (same as the theme files). There is an internal DataIO class in TGUI that parses these files and returns a tree structure (or goes from tree to text file for saving), so this class should be reused.

**Comment by AustinHaugerud** [comment]
I don't have a thorough knowledge of how TGUI works internally, so I can't claim I know a good solution to the Renderer/Logic issue. My experience with using components isn't in building my own UI system. Based on how I have used the pattern in the past however, the public object of something is really just a wrapper over all the components. So if I used it in a GUI library with widgets the logic functionality would be in a component as well, not just the renderer. The wrapper class would help the components communicate with each other as needed. I've seen some programs that use components so that the public object is literally nothing but an ID and then the components. This may not all be suitable for TGUI however, especially since if you tried it would require huge changes most likely. 

As for the colorschemes system I mentioned. In my current project I have a factory interface (all the methods are pure virtual functions). I then just have the derived classes overloaded to create the widgets in a certain manner. It doesn't create the renderers stand alone. I can however use it to create the widget, get its renderer, and plug it in to an already existing widget, then let the temporary widget be released from memory as I don't use it. It takes a fair amount of work creating a new colorscheme, but after that using it is pretty easy thanks to the renderers being their own module in the widget. If you merged the renderers back in with the widgets, this would be more difficult. I'd have to either create some sort of function that manually only copies over the rendering related variables, or I'd have to preserve the non-rendering related data, assign the widget to the other, then re-assign the non-rendering related data. This is one of the reasons why I'm a big fan of the component pattern. It allows you to sort of use a plugin plugout system. 

Apologies, I thought you meant instant load. Still I agree though yes, the way you have to load GUI's in 0.6 is very awkward and clumsy. Improving this shouldn't be too difficult however. 

Having something like a project file wouldn't effect how the actual GUI gets saved by TGUI. The project file would hold information that's not all necessary for the GUI to be loaded in some other TGUI app. My only concern with the sub UI's is that won't TGUI immediately load and create all the child UI's? So if you have a sub UI that you don't want open immediately, you'd have to get a hold of it and close it manually after loading the GUI from the file.

**Comment by texus** [comment]
We are getting a bit off topic, but this renderer discussion is more interesting to me. The choice of removing the renderers is purely based on the assumption that they aren't of any use to anyone, but if your use case can't be done (or is much harder) without the renderers then they should probably stay.

Is there any specific reason why you handle the renderers between widgets yourself and not just use the Theme class? Also how exactly do you "plug it in to an already existing widget"?

I just figured out that an entire renderer can be fully copied with just the following lines (not the most efficient way but it guarantees that you don't break the widget). So maybe I can give widgets a setRenderer function which executes these lines.
``` c++
auto oldRenderer = oldButton->getRenderer();
auto newRenderer = newButton->getRenderer();

auto propertyValuePairs = oldRenderer->getPropertyValuePairs();
for (auto pair : propertyValuePairs)
    newRenderer->setProperty(pair.first, std::move(pair.second));
``` 

> So if you have a sub UI that you don't want open immediately, you'd have to get a hold of it and close it manually after loading the GUI from the file.

And if you don't immediately load all sub UIs then it would give the user who wants them all visible more work. The easiest solution is probably to just set the visible property to false when saving from the form builder, that way you can load exactly what you want. But if necessary the gui can be changed to optionally specify which part of the file to load.

**Comment by AustinHaugerud** [comment]
Well it's useful to me, it'd be interesting to know what other people think however. 

For textured themes I simply use the already made theme system. In my current project however I wanted to be able to embed different color-based themes, so I went ahead and did that instead. It's not that I felt I could make a superior theme system by any means, I just decided to make a way to create color schemes that are embedded with the executable. 

I did something similar for changing the widget renderers. For some reason I didn't have to iterate through the properties though, odd. 

Good point with the sub UI's, they can just specify whether or not the sub UI will be shown. I think that'll be the most reasonable solution. Adding flags to specify whether or not it should be loaded is unneeded effort.

**Comment by texus** [comment]
I doubt there will be input from other people, I almost never get any feedback on design decisions. That is why a lot of decisions are made based on what I find a good idea on a particular moment.

If I add a setRenderer function then the renderer can technically be replaced by a new class (one that derives from the existing renderer). So this would allow making custom additions to the renderers and thus give it some use to have them separately. Although due to the heavy dependence with the private widget variables you probably won't be able to extend much. But I'll keep the renderers for now and then they can be rewritten in v0.8 perhaps. That is probably at least five years away so by then I guess I will have had some feedback :smiley:.

But I would really like to know how you handle the renderers (perhaps even see some code), that way I may be able to improve them. The theme should allow you to create color schemes inside your application as well, so if what you have is easier than my theme class then perhaps something can be changed to make my theme class more user friendly.

Actually you are not really supposed to access the renderers yourself, the idea was that everything would be done through a theme and that only when one specific widget has to change its look then you would use its renderer directly. I just haven't found the time yet to write a tutorial on how to properly use themes and renderers.

It seems like the theme class is missing a clone function though, it was once on my todo list but for some reason I never implemented it. I will probably add it soon, that way you can setup a theme, load widgets from it, clone the theme, make only a few changes and then load other widgets from the new theme.

**Comment by AustinHaugerud** [comment]
I understand haha, I think the problem is SFML itself doesn't have a massive user base compared to older media libraries like SDL, Allegro, or even people who prefer to use lower level toolchains like FreeGlut/OpenAL etc.. To top that off, a lot of people who create UI's in SFML don't use any GUI library at all. At that point most people who use libraries simply don't seem interested in giving feedback, they just want to use it. SFGUI has more discussion I think but it's mostly just between the team (2 or 3?) and not the users. Still I think a good idea for you is to pick a design plan, and try to keep it long term. Libraries become troublesome if they change radically too much, and you can't really afford to with your limited time and manpower haha.

I was referencing how I use them to illustrate the benefits of keeping the component pattern. To be honest however I probably should just be using your theme class. (I do for textured themes, just not color schemes) Part of the reason I didn't was as you said, you haven't gotten around to documenting it very well. Creating a color scheme with my system isn't really that easy however, you have to implement a creation method for each kind of widget, and it takes up 100 or more lines of code to fully implement a color scheme. It's simple, but it's tedious and repetitive. The only advantage really is it's very easy to embed in the executable without any file dependencies. As far as I know tgui theme's can do this as well however. Anyways, to see the unintelligent repetition.

```
tgui::Button::Ptr DarkTheme::createButton() // Repeat this for every single widget...
{
    auto button = std::make_shared<tgui::Button>();

    button->getRenderer()->setBorderColor(color_themes::lightdark);

    button->getRenderer()->setBackgroundColor(color_themes::dark);

    button->getRenderer()->setTextColor(color_themes::darkorange);

    button->getRenderer()->setBackgroundColorHover(color_themes::darkblue);

    return button;
}
```

This system I keep simply because

1.) It's optional, you can still do themes by i.e loading one with TGUI
2.) It doesn't really do any harm to the program

I thought I was changing the renderer with 

```
console_box->getScrollbar()->getRenderer() = theme->createScrollbar()->getRenderer();
```

That's why I was puzzled with the manual copying over of properties. Just using the assignment operator seems to work just fine for me. I did some more searching through your code and found out this can't work because there shouldn't be anyway to properly reroute the renderer's pointer to the widget anyways. This puzzled me, as it seemed to be working anyways. I knew it shouldn't have been working. I found out in my theme implementation I actually was setting the scrollbar for ChatBox by swapping out the scrollbar entirely which was taking precedence over the previously shown line. So that's an error on my part. (Yay, found a disaster waiting to happen!) Still, your method for swapping out the renderer soley works fine, so having a way to clone renderer components I think is a good idea. You can almost get away with a shallow copy, you'd just have to make the sure renderer is pointed at the right instance of the widget it belongs to. Your method you've already shown can do this fine, you'd just want to make it a method of the renderer itself of course. 

Thinking about it however, my idea of trying to use the assignment operator on a pointer type in the first place was quite naive. I suppose I've gotten away with this approach in some libraries (i.e Irrlicht I believe, but they anticipate this kind of usage, and it's still with a setComponent(...) style method for most things), but for TGUI it's not a good idea. The assignment operator should still just be avoided completely, and a clone method would be inherently clear and easy to use. If you try to have assignment operators thrown in the mix you have to specify the difference between assigning with the shared pointers vs actually assigning to the renderers themselves and it's all just unnecessary layers of complexity. 

Just an idea of something that's worked for me before with components. Sometimes it's worth adding a "mediator" class. This is like a messager system that the public object uses to share messages and data between components. It's nice because it allows for super high if not complete decoupling of the components. Normally it gets used when you have a larger collection of components however. Your current design is kind of halfway with using the component pattern. If it was fully componentized, not only would rendering be put in a module, the logic part would as well. The actual object being used would just be a wrapper around these and help manage how they work together. Going this far would probably annoy people if they had to do something like

```
myButton->getRenderer()->setColor(myColor); // <-- OK
myButton->getProperties()->setPosition(button_pos); // <-- Might annoy people
```

So if you went with a full component approach, you'd probably want wrapper methods
```
myButton->setPosition(button_pos);
// Underneath calls something like m_Properties->setPosition(button_pos);
```

Taking the component pattern this far would be more for modular maintainability I think. An easy example I can think of is that the position the renderer cares about is where on screen that widget needs to be drawn. It doesn't care about its position relative to its parent, it just needs to know the screen coordinates in its view. The logic component would be more worried about these kind of things. When you develop either section it's easy to focus on just that section (great for team development). The renderer component is nice for plug-and-play but beyond that I don't think it applies as much. You could easily do things like clone a labels position and text value without cloning its appearance, but that's all I can think of right now.

**Comment by texus** [comment]
Even if the createButton and similar functions would use the theme class you would still need the same huge amount of lines since you have to set the properties on the theme instead of directly on the widget. So using my theme class doesn't really improve anything here.

> console_box->getScrollbar()->getRenderer() = theme->createScrollbar()->getRenderer();

I thought that this was enough to stop you from doing that:
``` c++
ScrollbarRenderer& operator=(const ScrollbarRenderer&) = delete;
```
I guess assigning the shared pointer will use the copy constructor of the ScrollbarRenderer instead of the assignment operator which is why it works. And I need the copy constructor myself in the clone function so I can't delete it as well. I guess there isn't much use in deleting that assignment operator since that code of yours still compiles.

Although I would like to have a logic and renderer component the code is just too connected. Both classes need access to each others private parts all the time, they need to be friends which prevents custom renderers and an alternative like using messages would be bad for performance.

Things like mouse events belong in the logic part but they change the color of the currently displayed text which is more a renderer property. Actually the most difficult function to classify is the draw function. It really belongs in the renderer and having it fully in the renderer would allow a user to override the draw function and really change the way the widget is displayed independent of the logic part. But if there is one function that needs the most information about the current state of the widget then it is the draw function as it needs to display things depending on what the user is doing with it.

If I add getters to the renderer (which I intend to do) then the logic code would no longer need to access the private parts of the renderer, but the renderer would always need too much access on the widget (especially if it has the draw function) and I can't solve that problem. Both components are just too dependant on each other.

I guess I should really try to have a look if I can find another gui that has separate logic and rendering code and see how they managed to do it.

**Comment by AustinHaugerud** [comment]
> an alternative like using messages would be bad for performance.

To be honest, I think you're just making an assumption here. Correct me if I'm wrong, but TGUI doesn't aim to work on super low end hardware anyways. Plus there are games that use a messaging system for component communication in performance critical time for physics components, AI components, render components etc. In reality TGUI spends most of its time idle anyways, I'm sincerely worried if someone is managing to click a button 100 times per second or something of that sort. Messages only have to be broadcasted when something actually happens with the widgets. The renderer does have data it needs access to constantly, so this might become a question of hot vs cold data. Any hot data the renderer should keep directly. You're already doing this with things like the color. Something like its position is important as well, but as I said earlier the position the renderer is concerned with doesn't necessarily match the position the logic component is concerned with. Looking at how you're doing things right now, grabbing a random example with button

```
if (m_button->m_mouseHover)
            {
                if (m_button->m_mouseDown && m_button->m_mouseHover && m_textureDown.isLoaded())
                    target.draw(m_textureDown, states);
                else if (m_textureHover.isLoaded())
                    target.draw(m_textureHover, states);
                else
                    target.draw(m_textureNormal, states);
            }
```

To be honest this code in my opinion is complete blasphemy to the one of the points of using components, decoupling. 

> Although I would like to have a logic and renderer component the code is just too connected. 

Exactly, the point of the component pattern is to cure bad situations like these. You seem to be opposed to the component pattern because of your coupling. This is puzzling to me because I find it equivalent to saying "I'd go to the doctor but I'm too sick". Having the problem calls for using a solution, not rejecting it. 

Also, you seem to be worried about performance, but everytime you use `m_button` ,which you do many times every single frame, that's treating your logic related data as cold data, it's super high frequency pointer indirection. This is fine, I'm just saying, if you're concerned about making it fast to such an extreme level, this isn't really any better than a messager system. It seems silly to me anyways to try to optimize TGUI so much as I personally have never even come close to having a performance or memory issue with TGUI on a 4 year old regular laptop. For most SFML projects the bottleneck is rendering a tilemap, or running a physics simulation on thousands of objects. I cannot for the life of me imagine a project where someone would be bottlenecked by TGUI. If they are, there project is probably bottlenecked at something over 60 fps anyways (aka, bottlenecked with no actual performance issue). 

Keep in mind with a messager system, it only broadcasts a message when something actually happens. GUI interaction frequency doesn't even come close to how often you have to render a frame. So most of the time, your renderer's data doesn't need updated. In your code right now, it's checking all these things about whether or not the mouse is hovering on the widget, if it's being pressed etc. when on the vast majority of iterations, the state of things hasn't changed. Eventually it does, but there's a good chance your code will check this at least 30 times ( and easily more if there's no framerate limit etc. ) before the user even has a chance to perform some action again. 

You still have to update frequently enough for smooth detection, but there's really no need for it to update every single draw frame. It'd be sensible in my opinion to have the updating for the logic component done on a fixed timestep independent of how often the program is rendered. So for example, if the program is running at 120 fps, TGUI still can just check if a widget is being hovered on etc. 20 times per second. There is really no need to run 120 checks, it's just extra work with no real benefit. 

Now, this still doesn't address the really tight coupling between your renderer and the main widget (or if you went full component pattern, what would be the tight coupling of your renderer and logic components) I think it's worth considering adding state data to the renderer. Like I said, the state data doesn't need refreshed nearly as often as you need to render a frame. The renderer can just use the stored state data to determine how it needs to draw the widget. Every time TGUI runs an update on things, the state data can be refreshed. Your logic component could use the messager to notify your renderer of its new state it is to take on. Since the messager rarely actually has to be invoked, there shouldn't be any performance penalty (probably an improvement actually), as you're not using the messager every single frame. With that, your renderer never has to ask your logic component for anything directly, and your logic component doesn't actually have to send data to your renderer as near as often. 

Most of what I wrote there was with your draw functions in consideration. 

> Things like mouse events belong in the logic part but they change the color of the currently displayed text which is more a renderer property.

This is where you use the messager. As I said before, this messager doesn't need to be invoked that often anyways. On a fixed timestep, checks don't need to be made more often than they need to be, and the messager can make sure to only send messages when a change is detected. 

>  I guess there isn't much use in deleting that assignment operator since that code of yours still compiles.

I suppose, since you do everything with shared pointers anyways. As far as I know there's no way to change the behaviour for a pointer's (raw or smart) assignment operator. The only way to prevent the assignment is to use a const pointer which doesn't sound like a good idea to me. Hopefully most people won't be stupid like me and try something like I did.

**Comment by texus** [comment]
I was to lazy to come up with a decent reasoning because the post wasn't really about a message system so I just said performance as a reason, I guess I should have just not mentioned it at all.

I don't really care much about performance anyway, I do try to do less in functions that are called every frame (like draw) and do most of the work in functions that are called less often, but performance never comes on the first place when considering a design.

Although I already knew all of the things you said in your post, reading through it did made me think about these things a bit better. I don't even have to call things at a fixed timestamp like you suggest because everything depends on events, so I only update when a mouse move event is reported from sfml (only a few times per second) and most likely even less because I only have to send a message on the already existing MouseEntered and MouseLeft events.

I don't expect the amount of different messages to be an issue as I originally thought, but I fear there will be way too much duplicate variables. The renderer for e.g. MenuBar would also have to contain all the menus. Also almost every function that gets called on the widget would have to pass information to the renderer, because practically all setter functions changes the state. After taking a look at some draw functions I realize that I'm closer to being able to decouple the parts then I thought, but these issues still bother me.

The reason why I am more tempting to go back to a single class is because there was no issue there. All the problems that I have with the renderer only exist because it is in a separate class. Of course I would love to solve it by decoupling it more but I fear that I am just making compromises on solving a problem that I only created be decoupling it a little bit. That's why I'm trying to find a clean way of having the components, if I have to make too many compromises (e.g. using much more memory plus having to add a lot new code for the messages) then I might as well just return to the old version where there were no problems. Of course having components is a better system because it allows replacing only a single component.

**Comment by AustinHaugerud** [comment]
> The renderer for e.g. MenuBar would also have to contain all the menus.

Not necessarily. MenuBar isn't designed to expose very close control of the internal labels, you're expected to work entirely  on MenuBar renderer's terms. Because of this, it isn't necessarily that important to keep a copy of EVERYTHING concerning the menu and menu items. You could possibly just store some more shallow state information that is still organized based on menus.

```c++
struct ShallowMenu {
    sf::String m_name;
    std::vector<sf::String> m_items;
};
```

```C++
// In MenuBar renderer
std::vector<ShallowMenu> m_menus;
```

This doesn't allow for close control over how single menus or single menu items are rendered, but MenuBar already isn't designed for this. 

> e.g. using much more memory plus having to add a lot new code for the messages

How many menu bars can you expect to actually be allocated? I agree it's important to avoid duplicating too much memory when you expect for there to be a lot of something, but often times a person will make literally only one menu bar. A widget like label this makes more sense, as you can expect to have a lot of labels on the screen. Things like a menu bar or child windows however you can expect for there to be quite few of. 

> The reason why I am more tempting to go back to a single class is because there was no issue there. 

There wasn't the issue we're discussing now. Still however, this brings TGUI back to

- [x] No way to plug in a custom renderer
- [x] A monolithic object with less organization

which in my personal opinion is an issue. 

Adding the ability for custom renderers could mean a lot. Currently TGUI forces you to use SFML as your drawing medium, even if the rest of your project uses say your own opengl code. What if someone wants to add fancy shader effects to the rendering process for their UI? The default renderer can allow for people to still keep things simple, but the option for custom renderers also allows for more advanced use.

Currently TGUI seems to kind of be in an awkward middle of things. As the way it is currently TGUI has

- [x] No way to plugin in a highly customizable renderer ( only slightly customizable )
- [x] Widgets are still quite overly coupled with logic and renderering 

 I understand the concerns you have about duplication, but most widgets in TGUI you don't create too many of anyways. So even if you do duplicate a lot, in most widgets it would be very negligible. You can be smart about the state and duplicated data however. For one, state data can for many things be limited to small enumerated variables. For other things ( i.e. MenuBarRenderer and the menus ) you can do a very bare bones copy.

**Comment by texus** [comment]
Actually the ShallowMenu won't work. The renderer needs the full labels because he has to render then with the right color etc. Just storing the strings it not enough, the renderer has to draw everything so it even needs more information than the widget. In the logic part you would still need the labels as well unless you would only store rectangles but then you still have to go get the labels when you e.g. call setTextSize because you would have to recalculate all those rectangles. So you still need the labels on both sides. The same story goes for most widget, the renderer needs most of the information to do all the drawing, you can minimize some variables but there is still way too much duplication.

My problem isn't really with memory itself, my problem is with writing and especially maintaining it. Because you have to store so many things twice you make the code more error prone because you might change it somewhere and forget to change it at the other place. Having components is supposed to isolate things and make maintaining easier, but as I currently see it almost all operations have to be done on both components thus not making it any easier at all, it just makes my current code more difficult.

I don't have the time to do further research on it, but it seems like CEGUI has separate logic and renderers. So I guess it would be a good place to get some more inspiration from.

**Comment by AustinHaugerud** [comment]
I think we've discussed it enough for now. I have been working on this form builder just so you know. I've got some progress on made on allowing editing of properties for whatever item the user has selected etc. but I don't expect to have anything usable for a while yet.

**Comment by texus** [comment]
I have been thinking about splitting the logic and renderer code again recently. I'm currently thinking of trying it like this:
Current widgets will just become classes with functions, no member variables (unless perhaps a few, I haven't really looked at it yet) except for a pointer to a new WidgetState struct which contains the variables that that widgets currently contain. The draw function of Widget would simply be implemented as passing the state variable to the renderer in some draw call. Since the state will contain a boolean whether the state has changed the renderer only has to do recalculations or redraws when something changed in the state (e.g. new widget size) or in the renderer (e.g. new text color being used). Everything is rendered to a sf::RenderTexture and then drawn to the window (I need the render texture anyway for my opacity function to work correctly unlike the way it is implemented now). When nothing has changed since last frames the renderer just has to draw the cached render texture and thus reduces draw calls which is a nice extra side-effect. This means that all calculations that I am doing in setPosition, setSize, etc will all be done by the renderer and the renderer thus has full control about what gets drawn where. The widget classes themselves won't do much more than just changing the state and sending callbacks when things happen. I would need to create a new state class per widget which also has the same inheritance tree as the widgets (e.g. ButtonState has to inherit from WidgetState) which is why I originally didn't want to consider this way, but after some rethinking I guess it is a small price to pay to get the renderers completely in charge of all rendering and thus allowing fully customizable widgets. I haven't really looked into possible problems of this system though.

I don't really expect it by then, but do you think there will be a basic form builder by the second week of February? I'm just asking to know if it could be included already in the alpha3 version. After that there probably won't be any other release until August.

**Comment by AustinHaugerud** [comment]
If it's important to you I can try setting aside more time for it, but I can't guarantee anything yet sorry. I have it started but then I had to go through college finals, now I'm looking at moving out of town, etc. I haven't gotten a ton of coding done recently. I'll see what I can do and let you know the situation as soon as I can however.

**Comment by texus** [comment]
It's not important at all, I just wanted to get some idea of progress so that I wouldn't release alpha3 and afterwards find out it could have been added if I waited a few more days with the release.

**Comment by AustinHaugerud** [comment]
Fair enough, still I apologize for not keeping you up to date more. I'll write up some sort of progress report soon.

**Comment by AustinHaugerud** [comment]
Alright, well it's still definitely not done but I've put up the little I've done so far onto a git repo. https://github.com/AustinHaugerud/TGUI-Formbuilder

Definitely has lots of work needing done still and some issues already, but I'm working on it.

**Comment by AustinHaugerud** [comment]
What's your status on this right now? I know my project went cold turkey, but I'm still interested in helping you get a form builder going. Mine just wasn't panning out well and I got caught up in a lot of other things with work and college. If we can though I'm definitely willing to come back to this with you however. Maybe you could create a requirements and specification list/document of some sort for the Form Builder?

**Comment by texus** [comment]
There still isn't any progress on the form builder. I was planning to write one for 0.8-dev in a few months as I no longer believed anyone would do it for me 😄. But since the layout system is also going to be rewritten I would have probably delayed it even further. Although this shouldn't really impact the initial versions of the form builder.

I'll write a list of features that I expect in it later today.

Whether the form builder should be for 0.7 or 0.8-dev I will leave up to you. If I would write it I would only add it in 0.8-dev.

**Comment by texus** [comment]
Below you can find an unordered list of what I expect from the form builder. It's probably a lot of work to implement it all. If you do get some/most of it working then I'll probably be able to help with remaining parts after July, but I'm going to be too busy until then.

Initial version:
- [x] One 'editor' child window shows the widgets that you place, another 'properties' child window shows the properties of the selected widget and a third 'widgets' child window contains buttons to create widgets of various types.
- [x] On top of the properties window there should be a combo box to with all widgets to be able to switch to widgets that aren't visible in the gui (e.g. a label without text). This combo box should have a scrollbar when there are too many items to prevent the list to be larger than the properties window itself.
- [x] All widgets added to the editor window are disabled, they should not respond when clicking on them.
- [x] When the editor window is clicked, find out on which widget the click happened, select its value in the combo box and show its properties.
- [x] Selected widgets should have 8 little squares around them that you can drag to scale them.
- [x] Dragging a widget should move its position. This should not be per pixel but instead with steps of e.g. 10px.
- [x] The child windows should not have a close button as you should not be allowed to close them.
- [x] The title of the editor window is the filename to which it was last loaded from or saved to.
- [x] Widgets can only be added to the window directly, no hierarchy is supported with e.g. panels and child windows.
- [x] Properties and values are displayed next to each other. Properties could be an uneditable edit box while values are simply strings inside an edit box. No checks are in place whether the values are valid for renderer properties, they are given directly to the gui.
- [x] Properties for each widget (e.g. password char in edit box) should probably be hardcoded in the form builder. Although the propery names could be loaded from the config file as well, there is no dynamic way to change non-renderer properties.
- [x] A propery is not changed when typing in the value box, only when hitting the return key or when the edit box loses focus.
- [x] When a property is changed, the corresponding widget in the editor window is updated.
- [x] Keep track of windows where a change was made.
- [x] If something was changed in the window, the title will contain "* " in front of the name.
- [x] Editor windows have a close button that will ask you to save the changes if something was changed.
- [x] There should be an option to start a new form (removed the current one as there is only one editor window, warns that unsaved changes to it will be lost), an option to load a file and one to save the file. ~~This could be done by having a title bar.~~
- [x] Properties and widget windows are not scalable. Editor window should be scalable.
- [x] You should be able to copy and remove widgets. ~~This can be done by options in the menu bar.~~ There should be no separate paste command, hitting copy should immediately clone the widget.
- [x] There should be an option to move widgets to the back or to the front. ~~This can also be in the menu bar.~~
- ~~The form builder has a config file that tells it which widgets it can create. This file contains a list of widgets where each has an image (the icon in the widgets window) and a list of renderer properties and their types. This requires a bit duplication since a list of these properties could be extracted from the gui itself, but by doing it with a config file it will be possible to have accurate types and e.g. have a color picker inside the editor for every color property. Technically the syntax of this file does not matter, but since there is a DataIO class that is already used for both theme files and widget files it would be best to simply reuse it here.~~

Future additions:
- Multiple editor child windows can be open simultaniously.
- Widgets in the editor should have hierarchy. They can be recursively added inside each other. Not only widgets like child windows but also groups and layouts should be supported.
- The widgets window and property window should also be scalable. Initially the widgets window may e.g. contain 2 columns of widgets but if you increase the width then the amount of columns should increase or decrease accordingly. A minimum size is set to prevent the windows from getting too small (e.g. the widgets window should always display at least one column).
- An undo and redo button should exist to undo the last property change, move, scale, copy or remove action. Multiple actions should be undoable in a row.
- Shortcuts should exists to copy-paste a widget and to undo and redo a change.
- Different property types could be handled differently. For instance a color property should have a button next to it to open the color picker. A boolean property would get a combo box with only "true" and "false" as values, an integer or float value could be checked so that you can't write text in the value edit box.

**Comment by AustinHaugerud** [comment]
That's a pretty good list, I should be able to spend some time and work out a good plan on how to get started with this. Just to confirm, your priority is for this to go into v0.8? I think that would make sense. It's better to just acknowledge v0.7 missed the form builder and focus efforts on v0.8, not to mention by the time the form builder is ready v0.8 probably will be at least near completion.

**Comment by texus** [comment]
Yeah, 0.8 has priority.
It will also allow making changes in the gui when you find things that could be improved while creating the form builder. When developing for 0.7 you would have to make the changes in both 0.7 and 0.8 which is more work plus you wouldn't be allowed to make breaking changes in the gui.

**Comment by AustinHaugerud** [comment]
Alright, sounds like a plan. Do you have a way we can talk at times besides a forum? Something simple like a Discord channel? I'm going to need to talk with you here and there, and Github issues probably isn't best suited for that.

**Comment by texus** [comment]
I could create another room on Gitter. Or we can use something else if you prefer, I'm using Franz as chat app which supports practically anything.

**Comment by AustinHaugerud** [comment]
I haven't used those services. It looks like while Franz is handy in supporting so many services, that doesn't prevent you from having to make new accounts etc. If you want to use Discord Franz supports that, you just need to make a Discord account, and then set up a channel. Or you can just use Gitter or whatever else you like and I can hop on there, just let me know.

**Comment by texus** [comment]
It's a good opportunity to explore Discord.
I've created an account there, this is the invite link: https://discord.gg/tKrk7

**Comment by AustinHaugerud** [comment]
The Formbuilder repo has added issues corresponding to everything you've specified in your list. If you have anything else you think needs added, just go ahead and open an issue on the repo.

**Comment by AustinHaugerud** [comment]
An update, I've just had a really bad time crunch on work this semester. Once summer break starts I'll be back to work on this issue.

**Comment by texus** [comment]
Alright. I'm going to have time myself in July, so depending on how long I'm going to be busy rewriting the layout system, we can work on it together.

**Comment by AustinHaugerud** [comment]
I've finished finals, summer has begun. I'll be working on this again during weekends.

**Comment by AustinHaugerud** [comment]
It was originally my intention to try to keep the formbuilder somewhat friendly with custom widgets, but due to new complications I hadn't seen before and time restrictions, I'm thinking at least for now it's best we just stick to TGUI standard widgets.

**Comment by texus** [comment]
Yeah, custom widget support is definitely not a requirement.
I got some time myself to work on TGUI now that the summer vacation started for me two weeks ago (although its technically not really a vacation since I have to be searching for a job). I'm currently working on improving the .Net binding and afterwards I'm planning to have have a look at the Tab widget. But after that, I'll probably have time to work on the form builder myself.

**Comment by texus** [comment]
There is still a lot to do but I'm closing this issue now that the initial version of the Gui Builder is finished.
