### ISSUE TITLE
Proposition: Additional data in widget

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#48]
Sometime I need associate widget with additional data. Now i must do it by std::map or std::vector. But more comfortable would be get data direct from widget. Could you add to the widget additional pointer to external data? 
Below I join examples of function declarations.
```cpp
void *getAdditionalData() const;
void setAdditionalData(void* data);
```

**Comment by texus** [comment]
This won't happen, this is something you have to do in your own code. Instead of saving the widget just save a pair with the widget and the data or even a struct or use a map like now.

**Comment by klusekrules** [comment]
I don't mean here to save widget. I mean only stored this in the operating memory.

**Comment by texus** [comment]
Yeah, I mean storing instead of saving as well. I'm just not going to change my widgets to store data that are specific to your application. It is not the right way to do things, you should keep track of the data in your own code. Otherwise you can make this request to almost every existing library (I have actually seen similar requests being made a few times on the sfml forum).

**Comment by klusekrules** [comment]
Right, I see your point of view.
