### ISSUE TITLE
Stack Overflow when on loading widgets from file

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#56]
I get the same error as #54 when loading widgets from a file.
File where i receive this error:
```
Panel {
    Position: (150, 150);
    Size: (410, 110);

    Renderer {
        BackgroundColor: Transparent;
    }

    Picture.ObrazObiektu {
        Filename: "resource\\Brak_obrazka.png";
        Position: (5, 5);
        Size: ("&.h-10", "&.h-10");
    }
}
```

**Comment by texus** [comment]
I can't reproduce the issue. Are you certain you are not still linking to libraries from before the fix?
If you are sure you are linking the latest version, could you show some minimal c++ code that loads the file and reproduces the error so that I can be certain that we are testing with the exact same code?

Responding to the previous issue was enough, I still get a mail even when the issue is closed so you didn't really need to open a new issue. My thunderbird just wasn't updating my mails which is why I'm only seeing this now and not this morning already.

**Comment by klusekrules** [comment]
I make few tests and then i realize that i have mismatch in code. I was my mistake. Sorry to bother you.
