### ISSUE TITLE
Unicode display issue

### ISSUE THREAD

**Issue by MaverickTse** [texus/TGUI#65]
I have just give a try on this GUI toolkit, and find out the menu bar fail to display Japanese.

ScreenShot:

https://twitter.com/MaverickTse/status/778159853445455872

**Comment by texus** [comment]
You need to set a font that contains japanese characters. If these squares are drawn then it either means you passed an ascii string (not the case here because you have the L in front of all strings) or the font does not contain the glyphs that you need.

**Comment by MaverickTse** [comment]
It can be get around by specifying the font file:
![tgui_unicode_fix](https://cloud.githubusercontent.com/assets/10569988/18715037/57cb4288-804a-11e6-9afc-a15919e9d0fc.PNG)

but the problem is, the SFML window title do not need this at all. wxWidgets also do not need explicitly setting the font.
There has to be a way to simplify the process.

**Comment by texus** [comment]
The way that you won't have to set a font is when TGUI would ship with a font file that contained both english and japanese glyphs. But then at some point some other language would be needed as well so in order to support them all I would have to include a huge font file in the gui just for the few people who use some of these glyphs.

I don't know how the title or wxWidgets work but they probably use system fonts and may even use a different font depending on the locale of your pc. SFML isn't even responsible for the font in the title bar, that is something from the OS.

If you are going to use SFML then you are going to need to load a font anyway. I made it easy by including a font directly into the Gui class so that you can use it out of the box, but SFML doesn't even have a default font. If you want to render a text with SFML then you must load the font yourself.

But you do not have to set a font for all widgets. If at the beginning of the program you just call `gui.setFont("font-filename");` then all widgets that are created afterwards will use this font. So you basically only need one line of code to support japanese text.
