### ISSUE TITLE
[0.8-DEV]Label Color is missing ?

### ISSUE THREAD

**Issue by davedevils** [texus/TGUI#68]
Hello,

I have try tgui 0.8-dev for make it  my project (Multi-Game launcher) ...

Lot's of work is finish , i'm happy ... Now i create "light" interface

And i have see no option for change color of label, i can't downgrade to 0.7 at this point .

Can you add it please ?

**Comment by texus** [comment]
In order to change the looks (colors or textures) of a widget you should access its renderer. You can call `label->getRenderer()->setTextColor(sf::Color::Blue);` to change it. This was already the case in 0.7 but I had the function in both the renderer and the label there.

**Comment by davedevils** [comment]
thanks , sorry for asking this i have work with 0.6 but never in 0.7

I think a settextcolor directly can be good

**Comment by texus** [comment]
Yeah, for label it still makes sense to have it in the Label class itself which is why it was like that in 0.7. But then you basically have duplicated functionality, one function in the widget and one in the renderer that do exactly the same.

Because renderers can now be shared between widgets in 0.8-dev, things would get a bit more complicated if I had the function in both places. So I removed those few places where such duplicate function still existed and decided that you would just always have to access the renderer.

**Comment by davedevils** [comment]
Just i do not understend why not make rgb color and send it in function for no duplicated like -> if color == nulptr -> sf::Color(255, 255, 255) else sf::Color(userR, userG, userB)


By the way using like
label->getRenderer()->setTextColor(sf::Color(200, 200, 200));
versionlabel->getRenderer()->setTextColor(sf::Color::Blue);

all label go to the last color (blue) ...

**Comment by texus** [comment]
> Just i do not understend why not make rgb color and send it in function for no duplicated like -> if color == nulptr -> sf::Color(255, 255, 255) else sf::Color(userR, userG, userB)

I'm don't follow what you mean by this, but I think we are talking about something different. This doesn't have anything to do with the fact that I had two functions on different places that were executing identical code.

> By the way using like
> label->getRenderer()->setTextColor(sf::Color(200, 200, 200));
> versionlabel->getRenderer()->setTextColor(sf::Color::Blue);
> 
> all label go to the last color (blue) ...

This is by design. If you load widget from a theme, then all of them share the same renderer. Changing the theme or any of the renderers will update the other widgets that share the same renderer.

There are 3 solutions to this:
1. Don't use a theme. If you don't call the setRenderer function on the label then it will have a default renderer that is not shared with any other labels.
2. You want different labels to have different colors, so why are they loaded from the same section in the theme? The "label" string that you pass to theme.getRenderer is the name of the section in the theme file. You can define multiple sections in the theme each with different colors. So you would get something like `label->setRenderer(theme.getRenderer("MyLabelType_1"))` and `versionlabel->setRenderer(theme.getRenderer("MyLabelType_2"))` when creating the labels.
3. Clone the renderer. If at some point in the code you want get a new renderer that is not linked to the old one but still has the same properties then you can use the clone function. You would get something like `versionlabel->setRenderer(label->getRenderer()->clone());` in your code. After that `versionlabel->getRenderer()` will no longer be the same as `label->getRenderer()`.

Number 2 is what you usually want, but if you only need to set the text color for the label then number 1 is even simpler here.

**Comment by davedevils** [comment]
I understend but i can't use that because i load all like color,texte,pos from a xml ( i have a gui editor for do it) and i use theme by theme ...

So just i ask only for a simple function in 0.8 for add color directly in design , for the moment i think i make like 7 color by using the second way.

The actual solution it's not great because you can't by exemple make a red text for error with some explain in blue or change color by fast way like i do.

**Comment by texus** [comment]
I don't see why you can't use option 1.
Things like errors or explanations are different things so it doesn't make sense to load them from the same section in the theme. Having a section for each makes more sense.
But if you need a label that can change its color easily and fast then don't load it from the same section as you load other labels. Either don't call label->setRenderer at all or if you really have to then just pass a unique section. You can still use label->getRenderer()->setTextColor to change the color later, but only if you don't have multiple labels connected to the same theme section.

**Comment by davedevils** [comment]
I can't use option 1 because i using theme system , i changing it at running but ok i understend you not want they use other way .

I use option 2 thanks
