### ISSUE TITLE
Parts of <functional> deprecated in C++17 - TGUI doesn't compile with /std:c++17 in Visual Studio 15.3

### ISSUE THREAD

**Issue by JayhawkZombie** [texus/TGUI#75]
Much of the ```<functional>``` header is deprecated in C++17 (all of the binders and adapters were deprecated, and they're completely removed in the implementation I have).

In ```Global.hpp```, the ```trim``` method has 2 lines:  
```cpp
str.erase(str.begin(), std::find_if(str.begin(), str.end(), std::not1(std::ptr_fun<int, int>(std::isspace))));
str.erase(std::find_if(str.rbegin(), str.rend(), std::not1(std::ptr_fun<int, int>(std::isspace))).base(), str.end());
```  
that can be replaced with  

```cpp
str.erase(str.begin(), std::find_if(str.begin(), str.end(), [ ](int c) { return !isspace(c); }));
str.erase(std::find_if(str.rbegin(), str.rend(), [ ](int c) { return !isspace(c); }).base(), str.end());
```

Changing that allowed TGUI to compile in VS2017 with the /std:c++17 flag enabled.  Plus I think the lambda version is easier to read anyway.

**Comment by texus** [comment]
It's funny that it now no longer works in VS with these functions, because the only reason they were added in the first place was because VS couldn't compile
`str.erase(str.begin(), std::find_if(str.begin(), str.end(), ::isspace));`

Feel free to open a pull request with your change, so that I can merge the commit under your name. But please remove the space in "[ ]" to be conform with the rest of the tgui code when you do.
