### ISSUE TITLE
Easing Animations

### ISSUE THREAD

**Issue by JayhawkZombie** [texus/TGUI#78]
I know TGUI has animations, but given the increase in usage of highly-animated interfaces and the shift away from linear animations, I think TGUI would benefit from some more "natural" animations.
By "natural" I mean animations whose behavior speeds up/slows down, etc, as one might expect to be exhibited by a real-world object.

For instance, a progress bar's filling speed accelerating initially and decelerating when it approaches its final value.

In Android's native UI, this is done using a CubicBezier interpolation method, and one can find countless "easing curves" online.
(Google has discussion about easing [here](https://material.io/guidelines/motion/duration-easing.html#duration-easing-natural-easing-curves))

It's not hard to implement on top of TGUI, but I think it would be more efficient and fit more nicely if it were native to TGUI.

A GIF wouldn't really demonstrate the difference well, so I opted to take a video showing the diff when using easing for animations vs just linear animations.  
[![Easing Animations](https://img.youtube.com/vi/DOAWJymDBcg/0.jpg)](https://www.youtube.com/watch?v=DOAWJymDBcg)

Cubic Bezier has a simple formula: B(t) = P0(1-t)^3 + 3P1t(1-t)^2 + 3P2t^2(1-t) + P3t^3

For example, interpolating a ```sf::Vector2f``` value:
```cpp
sf::Vector2f compute(float time)
{
  sf::Vector2f interp = sf::Vector2f(0.f, 0.f);
  float a = 1 - time;
  float b = a * a; // (1 - t) squared
  float y = time * time; // t squared

  interp += 3 * b * time * P1; // 3 * P1 * t * (1 - t)^2
  interp += 3 * a * y * P2; // 3 * P2 * t^2 * (1 - t)
  interp += y * time * sf::Vector2f(1.f, 1.f);
  return interp;
}
```

Given the way TGUI does its animations, I think easing animations could be added as an additional derived class of tgui::priv::Animation, but the constructor would need to accept 4 floating point parameters, as the interpolation curve needs 2, P1 and P2.

If you think TGUI would benefit from this, I suppose an interface should be discussed so it can follow the patterns followed elsewhere in TGUI.

**Comment by texus** [comment]
I have my doubts whether this would benefit a progress bar which you used as example. Wouldn't the filled part depend on "progress" made in a task as opposed to being defined by some animation? It feels wrong to me that a progress bar would be filling at a "fixed" speed instead of depending on some external factor. So I'm not convinced yet that this is needed in progress bar.

But I do see the use for other cases (e.g. moving a widget from one place to another). TGUI doesn't truly support animations, the show and hide animations are just a simple layer to provide a minimal animation support. The design should thus not be limited to the current Animation class. When I wrote the existing Animation class, the idea was to rewrite it into a more advanced design later, but I haven't had the time for it.

I unfortunately don't have the time for this, so it probably won't be added unless you (or someone else) contribute it. Feel free to propose better animation designs and maybe even write the necessary code. If I feel that it might be useful to others and if it doesn't make things too complicated then I would gladly merge better animation support into TGUI.

The existing animation code is allowed to be completely replaced, so there aren't many limitations for the interface. It should just preferably be easy to use with ideally the advanced features not making the simple features harder to use. Whether the interface focuses only on the position/size/opacity of widgets or whether you want to make a much more complex system that can be used internally by widgets (to e.g. have a menu in a menu bar slide open) is entirely up to you.

**Comment by texus** [comment]
I'm going to close this issue because it is not something that I plan to implement anywhere soon so I see no reason to keep this issue open. If you or someone else wants to contribute code that adds animation support then feel free to reopen this though.
