### ISSUE TITLE
Table widget

### ISSUE THREAD

**Issue by IvanFon** [texus/TGUI#83]
It looks like a table widget was being implemented at some point (#31) and later [removed](https://github.com/texus/TGUI/commit/d18b45317a60c63d6b6913cf9018831012930a56). Are there any plans to add it back in?

Thanks!

**Comment by texus** [comment]
There have been many requests for things like tables, multi-column listboxes, list views, etc. which are all very similar to each other but people need slightly different features in it. So this kind of widgets is wanted and on my TODO list, but there are no currently no plans to actually implement it because it's so much work.

The previous implementation wasn't started by me, someone contributed an initial version ([forum post](https://forum.tgui.eu/feature-requests/table/)), which I then patched and shipped in TGUI 0.7 in a WIP status (it had to be included manually to use). I wasn't entirely satisfied with the class and with all the changes I had to make in it to make it compatible with 0.8 I just decided to remove it.

**Comment by IvanFon** [comment]
@texus Would you be open to a PR for a multi-column ListBox? I’d be happy to try implementing it.

**Comment by texus** [comment]
Absolutely, I'd happily accept such PRs.

**Comment by texus** [comment]
I've started writing such a widget myself. An initial version will likely be included in TGUI 0.8.3
