### ISSUE TITLE
TextBox scrollbars hover color not changing properly

### ISSUE THREAD

**Issue by xandayn** [texus/TGUI#87]
The TextBox scrollbars don't properly change their hover color from highlighted to normal when moving from the scrollbar into the TextBox edit area. A solution for this is to call mouseNoLongerOnWidget() on them in the [mouseMoved function of the TextBox](https://github.com/texus/TGUI/blob/6383e6e787d34b2ff6a350407a7a72db99fd9673/src/TGUI/Widgets/TextBox.cpp#L532) like so:
```C++
// src/TGUI/Widgets/TextBox.cpp (543)
if (m_verticalScrollbar->isShown() && ((m_verticalScrollbar->isMouseDown() && m_verticalScrollbar->isMouseDownOnThumb()) || m_verticalScrollbar->mouseOnWidget(pos)))
{
// ...
else
{
    m_verticalScrollbar->mouseNoLongerOnWidget();
    m_horizontalScrollbar->mouseNoLongerOnWidget();
}
```

However I think there is a bug somewhere inside of the Scrollbar code itself as I feel the TextBox shouldn't have to manage keeping track of when it's scrollbars are being hovered or not.

Note that this solution is already implemented in the [TreeView widget](https://github.com/texus/TGUI/blob/6383e6e787d34b2ff6a350407a7a72db99fd9673/src/TGUI/Widgets/TreeView.cpp#L721)

**Comment by texus** [comment]
It's not a bug in scrollbar, it is how the code was designed. The mouseMove function can only be called when the mouse is on top of the widget (because the container already needs to decide this to figure out which widget is below the mouse and it would thus be unnecessary to do the check again inside mouseMove). So it is the job of TextBox to inform the scrollbar that the mouse is no longer on top of it.

This was obviously designed like that without scrollbars in mind. The Container class is normally responsible of relaying the right events to its children, but in case of sub-widgets like the scrollbar the widget containing the scrollbar suddenly has to do all the work. So calling mouseNoLongerOnWidget inside TextBox::mouseMoved is currently the right solution, but I'm always open for suggestions on how the scrollbars can be changed to make it easier to use them as sub-widgets. Widgets already use a ScrollbarChildWidget instead of using the Scrollbar class directly, so maybe some functionality could be implemented in that class.

**Comment by xandayn** [comment]
I see what you mean, that would also explain why it properly changes it's hover state when you move your mouse out of the TextBox as well, regardless, the simple change I mentioned earlier does fix the issue at hand for now. I'll make a pull request with the fix I proposed earlier.
