### ISSUE TITLE
Default RenderState in draw functions

### ISSUE THREAD

**Issue by abarichello** [texus/TGUI#89]
Hello, would it be ok to make `draw` functions that receive a `sf::RenderStates` have a default parameter? 
It would bring the implementation closer to what is used in classes such as `sf::RenderWindow`:
```cpp
void draw (const Drawable &drawable, const RenderStates &states=RenderStates::Default)
```

**Comment by texus** [comment]
The problem is that just adding a RenderStates to the Gui::draw function doesn't work. If you use a RenderStates to e.g. shift all widgets 100 pixels to the right, then everything will draw correctly, but at the time the events are handled (when calling Gui::handleEvent), the gui doesn't know that everything will be shifted 100 pixels so the widgets will react as if they were still on their unshifted location.

You could add it to both handleEvent and draw, but in a design where drawing and handling events are separated you might not have a RenderStates when handling events.
So what exactly do you need it for? Maybe there are other ways to accomplish it (e.g. using Gui::setView).

**Comment by abarichello** [comment]
What about the `draw` function in `Sprite.hpp`? It is currently implemented like this:
`void draw(sf::RenderTarget& target, sf::RenderStates states) const;`
I always used the default render state with SFML so i wondered why i had to make it explicit here, just a minor detaill.

**Comment by texus** [comment]
The tgui::Sprite class is for internal use in TGUI, it isn't supposed to use it directly in your code. What are you trying to do with the Sprite exactly?

**Comment by abarichello** [comment]
Issue discussed and resolved on Gitter channel, thanks @texus!
