### ISSUE TITLE
Question about Signals

### ISSUE THREAD

**Issue by 1aam2am1** [texus/TGUI#94]
Why?

    tgui::EditBox box;
    box.connect("TextChanged", [](tgui::Widget::Ptr){});//not working => unbound parameters
    box.connect("TextChanged", [](tgui::Widget::Ptr, sf::String){});//working
Shouldn't the first signal work too?

**Comment by texus** [comment]
Every signal can either have no parameters or a Widget::Ptr plus an sf::String. Just a Widget::Ptr isn't implemented. Even though technically these 2 parameters are unbound too, when I talk about "unbound parameters", I only refer to the ones that come after these two and depend on the widget and signal.

There is a reason the single parameter isn't implemented. There are signals that can have an unbound string parameter. So if I were to allow `[](tgui::Widget::Ptr){}` then when the user passes an `[](tgui::Widget::Ptr, sf::String){}`, would it mean the string is the signal name or the unbound parameter (e.g. caption of pressed button)? I might be able to make this unambiguous in the code, but it might be confusing (e.g. the string parameter would always give the button caption unless when you also want a widget pointer in which case it suddenly turns into the signal name). There might also be a conflict with the ChildWindow callbacks, which have an unbound ChildWindow::Ptr parameter and thus already accept a function like `[](tgui::ChildWindow::Ptr){}`.

**Comment by 1aam2am1** [comment]
Although I understand the reason that if we want get the widget::ptr we will have to accept everything coming with it. It should be somewhere documented.

**Comment by texus** [comment]
Any suggestions on where it should be documented? I wouldn't even know where to put it so that people would find it.
I would think [the tutorial](https://tgui.eu/tutorials/0.8/signals-introduction/) (which apparently doesn't even use the term "unbound" anymore) would be the best place, but to me it doesn't imply that it is possible to only have one of these two in your function. But feel free to suggest improvements.

**Comment by 1aam2am1** [comment]
We could set comment before: TGUI_SIGNAL_VALUE_DECLARATION(Int, int)
Or we could set it in SignalWidgetBase::connect 
Or even before signal class. But we can't by signal::connect connect functions others than std::function<void()> or std::function<void(std::shared_ptr<Widget>, const std::string&)> and that would be the worst place to write that. 

Based on TGUI_DEPRECATED comments everywhere in Signal.hpp shouldn't signal::connect be deprecated as well? Because before we could use connect function from SignalInt to connect to std::function<void(int)> or std::function<void(std::shared_ptr<Widget>, const std::string&, int)>.
now when defining TGUI_REMOVE_DEPRECATED_CODE we can only connect these function by SignalWidgetBase class.

Removing access to Signal property in widgets should be your purpose?

**Comment by texus** [comment]
The Signal properties in widgets are indeed going to become private (protected actually) in TGUI 0.9, which is why the connect functions have been deprecated. Technically Signal::connect should be marked deprecated too, but it is used from inside the TGUI code (and it will still be used from these places after the signals become private). The only access will be through the SignalWidgetBase class, which is also the only way described in the tutorial.

Looking at the descriptions in SignalWidgetBase, the parameters are briefly mentioned when TGUI_USE_CPP17 isn't defined (and it is never defined as that option isn't even documented):
```
Callback function that is given the extra arguments provided to this function as arguments
```
vs
```
Callback function that is given a pointer to the widget, the name of the signal and the extra arguments provided to this function as arguments
```

In the TGUI_USE_CPP17 code there is no mention at all, so at the very least I should add something there.

**Comment by 1aam2am1** [comment]
When you make signals protected.
There could be static/constexpresion variables with signals names. When using that variables we will have check in compile time that we don't misplace some characters in signal name. 

For now we could mark these functions deprecated, and create new functions and use them inside tgui. But this will be to much work for renaming evry single occurrence. 

Next I have seen Todo comment to implement signals to form. And that is impossible unless we add new class. It that class we will register functions by specific names or ID's. And when we load our form we simply connect our signal to this global class. This is my suggestion, but I don't know what vision you have to this.

**Comment by texus** [comment]
> There could be static/constexpresion variables with signals names.

Good idea. Do you think the constant should just be `tgui::Button::Pressed`?

> And that is impossible unless we add new class. It that class we will register functions by specific names or ID's. And when we load our form we simply connect our signal to this global class.

I was thinking about setting a single event handler in the gui (or the container widget that you are loading from a file) which takes a Widget::Ptr and signal name as parameter. That should be enough to identify all different callbacks. Maybe some unique callback ID could be used as well as alternative to using the widget pointer and signal name to identify the callback.

I haven't given it much thought yet though. Your suggestion would work too, but would require more code to connect the callbacks. On the other hand, except for small projects the user would write such code to send the signal to different places themselves anyway because you don't want to handle everything in one place.

Another solution would be to let the gui builder generate some c++ code (e.g. to let a button called `Button1` call the `Button1_pressed` function which the user then has to define in their own code). But that reduces functionality and would require a code recompilation when changing the form.

**Comment by 1aam2am1** [comment]
> I was thinking about setting a single event handler in the gui (or the container widget that you are loading from a file) which takes a Widget::Ptr and signal name as parameter. That should be enough to identify all different callbacks. 

I think this is bad idea, because if we have name of widget to witch we want to connect callback to, then we can simply search by name our container. 
I don't know for what user could use tgui signals from form, but we could simply this and call callbacks from form by name. By example our button registers callback to our class witch name "xyz" and we in our c++ code can check if that callback witch that name was registered and then connect that callback to our function. Or simply connect the callback with some name to our class and then load form and check or not if the callback was connected. If not the form simply don't have some functionality we have in our program. We can also add error name callback if form have run some callback that was not implemented in c++

**Comment by texus** [comment]
> I think this is bad idea, because if we have name of widget to witch we want to connect callback to, then we can simply search by name our container.

What do you mean? That it would be better for the function to get the name of the widget and the signal type?
Any idea that I've had about loading the signals from the form file had its good and bad points, which is probably the main reason why it hasn't been implemented yet. So it's a good thing for me to hear what others think about it.

> we could simply this and call callbacks from form by name. By example our button registers callback to our class witch name "xyz" and we in our c++ code can check if that callback witch that name was registered and then connect that callback to our function. Or simply connect the callback with some name to our class and then load form and check or not if the callback was connected

Could you perhaps show some examples of what it would look like, because I didn't fully get what you meant here. Do you have something like `gui.connect("Button5_Pressed", [](){});` in mind?

**Comment by 1aam2am1** [comment]
I didn't understand what you have said before.

I mean. In form we daclare callback button5_pressed. In tgui we call global signal container and set callback handler. With maybe tgui::widget and signal name or something that you have said. 
We can also set callback handler that if we don't handle it with registered callbacks it will execute it. Like error handler.

    auto c = tgui:: SignalContainer::get();
    t.register("Button5_Pressed", some_func);
    t.register("default", error_func);
    //egzamle load form
    t.check_if_connected("Button5_Pressed");
    t.get_names_of_not_connected();
    t.get_names_of_not_registered();

Something like that I think. Also we coul add a scope of working with this like loading difrents forms in difrents panels and calling local signal container
