### ISSUE TITLE
Handling more than left mouse button releases

### ISSUE THREAD

**Issue by Lidgnut** [texus/TGUI#96]
I need a Widget wich can react to all mouse button releases. Specificially Left, Right and Middle.

I found the ``` tgui::Container::handleEvent(sf::Event& event) ``` function, for the ``` tgui::Container ``` class in wich every gui element inside ``` tgui::Gui ``` seems to be contained.

Below is a snipped for handling "a" mouse release, out of ``` tgui::Container::handleEvent(sf::Event& event) ``` :

```
        // Check if a mouse button was released
        else if (((event.type == sf::Event::MouseButtonReleased) && (event.mouseButton.button == sf::Mouse::Left))
              || ((event.type == sf::Event::TouchEnded) && (event.touch.finger == 0)))
        {
            Vector2f mousePos;
            if (event.type == sf::Event::MouseButtonReleased)
                mousePos = {static_cast<float>(event.mouseButton.x), static_cast<float>(event.mouseButton.y)};
            else
                mousePos = {static_cast<float>(event.touch.x), static_cast<float>(event.touch.y)};

            // Check if the mouse is on top of a widget
            Widget::Ptr widgetBelowMouse = mouseOnWhichWidget(mousePos);
            if (widgetBelowMouse != nullptr)
                widgetBelowMouse->leftMouseReleased(mousePos);

            // Tell all widgets that the mouse has gone up
            // But don't do this when leftMouseReleased was called on this container because
            // it will happen afterwards when mouseNoLongerDown is called on it
            if (!m_handingMouseReleased)
            {
                for (auto& widget : m_widgets)
                    widget->mouseNoLongerDown();
            }

            if (widgetBelowMouse != nullptr)
                return true;

            return false;
        }
```
So as we can see here, the ``` tgui::Container ```, only ever checks if the Left mouse button was released, never for any other mouse button. I propose this could be changed and it could check for every other mouse button. To get that change propogated trough all of the rest of the called functions, it should be possible to add a ```mouseReleased(sf::Vector2f, sf::Mouse::Key)``` function to the Widget. To make the calling code kinda easier, the new ```tgui::Widget::mouseReleased(sf::Vector2f, sf::Mouse::Key)``` function can call ``` tgui::Widget::LeftMouseButtonPressed(sf::Vector2f)``` when the given key is ``` sf::Mouse::Key::Left```

**Comment by texus** [comment]
I'll see if I can add the functionality (probably today).

Currently there is a leftMouseReleased and a mouseNoLongerDown function. The first tells the widget that the mouse button was released when the mouse was on top of the widget, the second one informs the widget that the mouse has gone back up, irrelevant of where the mouse is. I think mouseNoLongerDown was added to aid with dragging (e.g. when dragging a scrollbar thumb and the mouse is outside of the scrollbar, the scrollbar should still know when the dragging stops). Do you think something like mouseNoLongerDown would have some use for other mouse buttons, or should I only add the mouseReleased function which takes the mouse position into account?

Now that I'm looking at the code again, I guess I can optimize the way mouseNoLongerDown is currently handled as well. If the container keeps track of the widget that received the mouse down event, it only has to tell that widget that the mouse went back up instead of calling the function on all widgets.

**Comment by Lidgnut** [comment]
> Do you think something like mouseNoLongerDown would have some use for other mouse buttons, or should I only add the mouseReleased function which takes the mouse position into account?

I guess it would be nice to drag and drop with any other mouse button. I'm thinking about inventory management. For example the user could start dragging with the left mouse button and it would drag all of the items in that stack and with the right mouse button it would only transfer half. Wich would be a nice thing to have.

Also thanks for the quick reply :)

**Comment by texus** [comment]
For now I've decided to only add the mousePressed and mouseReleased functions, I can still add a mouseNoLongerDown function later if needed. It's probably needed for drag and drop, but I'm not sure how it would best be implemented even with the left mouse button so it is a use case that I should think a bit longer about before adding stuff for it.

After implementing the changes suddenly half of my tests started failing (probably because a corrupted virtual function table). Turns out that if you compile a library with a virtual function and then use the library with that unused function removed from the class declaration, weird things happen. No crashes, no warnings in valgrind, but both gcc and clang just completely skipped the execution of SOME virtual function calls. I probably spend more time debugging that then actually implementing the mouse release code.
