### ISSUE TITLE
tgui::TextBox text selection changes

### ISSUE THREAD

**Issue by LarsHagemann** [texus/TGUI#97]
Hi Texus,

first of all, thanks for this awesome gui library :). In my opinion though, you should change something about the TextBox class and how the selection works.

The problem:
Someone needs to know the indeces (for comparison reasons or something else)
One could do the following:
```C++
// wasn't sure if sf::String::getSize returns the number of bytes
// SFML only says number of characters, though they could mean 32 bit
// code points as well. With toAnsiString().length() we get the number of bytes
auto length = textbox->getSelectedText().toAnsiString().length();
auto selectionEnd = textbox->getCaretPosition();

// the selection ends at the caret position and begins length bytes before it
auto selectionBegin = selectionEnd - length;
```
This code is not correct though. If a user does not select from top to bottom, the selectionBegin will actually be the caret position and the end should be the caret position plus the length.

So we would need code that looked like this:
```C++
auto length = textbox->getSelectedText().toAnsiString().length();
auto cp = textbox->getCaretPosition();
unsigned 
    selectionBegin = 0, 
    selectionEnd = 0;
if(textbox->selectedTopToBottom())
{
    selectionEnd = cp;
    selectionBegin = selectionEnd - length;
}
else
{
    selectionBegin = cp;
    selectionEnd = selectionBegin + length;
}
```
Since there is no such function as tgui::TextBox::selectedTopToBottom and the code looks kind of ugly, i propose two methods to resolve the problem (I prefere the latter one).

1. Let tgui::TextBox::getSelectedText return a pair of indeces, so that tgui::TextBox::findTextSelectionPositions would become redundant.
 2. Make tgui::TextBox::findTextSelectionPositions public. 

Since tgui::TextBox::getSelectedText should - intuitively - return a string of the selected text, I think the second option is the better one. It gives easy access to the string, while not taking the possibility of using the indeces directly. 

If there is anything I've overlooked, please tell me (or actually don't, this was quite some work :))

Ohhh, and a onTextSelection signal would be a charm. But I haven't looked in the signal system yet. So that's just a wish on my list.

Lars

**Comment by texus** [comment]
The reason why there is no access to the start and end index is because there wasn't any use for it yet. What exactly is it you are trying to do that requires knowing the exact indices? Maybe there are additional improvements that could be made to make what you want easier.

Same for onTextSelection. Although I can imagine some case where it could be used, I would prefer that you to explain how you would use it. Do you want the signal to fire every time the selection changes (i.e. while still dragging) or only when the mouse goes up and the dragging ends? What is the use case for knowing the selection?

I'm sure you have valid reasons to request it so it is likely that I will add these functions, but I prefer to know why features are needed before adding them.

> Since tgui::TextBox::getSelectedText should - intuitively - return a string of the selected text, I think the second option is the better one

I agree that getSelectedText should continue to return the text and that it would be better to make findTextSelectionPositions public, although maybe it could get a better name when it becomes public. Or maybe I should just add 2 functions: getSelectionStart and getSelectionEnd?

> // wasn't sure if sf::String::getSize returns the number of bytes
> // SFML only says number of characters, though they could mean 32 bit
> // code points as well. With toAnsiString().length() we get the number of bytes

Aren't characters and code points the same for UTF32? I know UTF8 and UTF16 may require multiple "code units" to store a code point, but in UTF32 every unit is 4 bytes which is more than enough to contain any code point. So is there a situation where you believe the value of `getSize()` can be different from `toAnsiString().length()`? (I'm asking this out of interest, I don't know much about unicode other than what I learned when writing my own string class recently)

**Comment by LarsHagemann** [comment]
> So is there a situation where you believe the value of getSize() can be different from toAnsiString().length()?

Thas's exactly what I wondered, and since I didn't know better I used the standard version. If there is one thing I really dislike about programming, it's text interpretation and encoding.

> What exactly is it you are trying to do that requires knowing the exact indices?

Currently I'm writing a Hex Editor, where you can select text in the hex view (which is just a read-only textbox) and it should highlight the corresponding ascii bytes in the ascii view (just like the hex view, this is a read-only textbox). And for that I need the indeces of the selected text, so that i can calculate the offsets, because one representation shows hex strings and the other raw bytes. 

> Or maybe I should just add 2 functions: getSelectionStart and getSelectionEnd?

I think another name would be good, since tgui::findSomething is not really in the style of tgui. It should become getSomething, though I cannot think of a good name. 
As far as I can tell, writing two functions would create a bit of an overhead because you either have to change the way findTextSelectionPositions works (so that you can write 
```C++
TextBox::getSelectionStart()
{
    return findTextSelectionPositions().first;
}

TextBox::getSelectionStart()
{
    return findTextSelectionPositions().second;
}
```
At the moment you would have to check the indices and swap them in each of the functions, which I think is unnecessary if you implemented the swap in the findTextSelectionPositions function. Though I don't know what kind of changes in other functions that requires (Actually though, I don't think it could becone a problem).

> Do you want the signal to fire every time the selection changes (i.e. while still dragging) or only when the mouse goes up and the dragging ends?

I cannot think of a usecase where it's useful to get the event everytime the selection changes. But maybe that's just me. One could name one signal onTextSelect and if anyone needs the version that fires everytime the selection changes they could implement it themselves and name it onSelectionChange and make a pull request.

**Comment by texus** [comment]
I just had a look at how findTextSelectionPositions is implemented and it does separate calculations for the start and end indexes. So it should be easy to split it up in 2 functions without creating overhead (the lambda should just become a separate function that can be called from getSelectionStart and getSelectionEnd).

So I'll add getSelectionStart and getSelectionEnd functions and an onTextSelect signal tomorrow or the day after.

**Comment by LarsHagemann** [comment]
Thanks a lot. Will onTextSelect take a sf::String parameter or to indices?
And should I close this request now?

**Comment by texus** [comment]
The getSelectionStart and getSelectionEnd functions have been added, I still have to implement onTextSelect.

The github issue can remain open until I'm finished, I close it myself when the changes are finished.

> Will onTextSelect take a sf::String parameter or to indices?

I didn't think about that earlier, but I'm currently considering to do neither.
Sending parameters might provide some minor performance loss when you aren't connecting the signal or not using the parameters. The onTextChange event can just pass a reference to the text while onTextSelect has to create a new string or calculate the indices each time before it even knows whether or not it is going to need them.
When you receive the callback, you can always access the text box yourself to get the data you are interested at. If you don't store the text box in your own code then you can always use add the `std::shared_ptr<Widget> widget, const std::string&` parameters to your function and use `widget->cast<tgui::TextBox>()` to get the text box.
On second thought, letting your function take a `tgui::TextBox::Ptr` parameter and passing the text box as extra parameter to the connect function is probably easier than having the extra unused string parameter and having to do the cast.

I realized that dragging isn't the only way text can be selected. For dragging it is easy to only trigger the event only when the mouse is released, but when holding the shift key and pressing arrows the event would be fired many times when selecting text. I haven't actually looked at this part of the code yet, but maybe it might be better to implement triggering the onTextSelect somewhere that all the code uses instead of on many different places. This would probably let the event trigger for every change, even during dragging (although that could easily be worked around by setting a bool flag during drag). But don't hex editors already select corresponding text while dragging too?

**Comment by LarsHagemann** [comment]
> But don't hex editors already select corresponding text while dragging too?

Well, now that you mention it ^^. What about a function like finishTextSelection() that is called whenever the shift key is released or the mouse dragging is over. In the finishTextSelection() funciton you could then fire the onTextSelect signal. 

Maybe that's something to think about.

**Comment by texus** [comment]
I ended up adding an onSelectionChange signal which is also called during dragging.
